// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: achievements.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createAchievement = `-- name: CreateAchievement :one
INSERT INTO achievements (id, user_id, group_id, season_id, achievement_type, metadata)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, group_id, season_id, achievement_type, metadata, earned_at
`

type CreateAchievementParams struct {
	ID              string                `json:"id"`
	UserID          string                `json:"user_id"`
	GroupID         string                `json:"group_id"`
	SeasonID        sql.NullString        `json:"season_id"`
	AchievementType AchievementType       `json:"achievement_type"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateAchievement(ctx context.Context, arg CreateAchievementParams) (Achievement, error) {
	row := q.db.QueryRowContext(ctx, createAchievement,
		arg.ID,
		arg.UserID,
		arg.GroupID,
		arg.SeasonID,
		arg.AchievementType,
		arg.Metadata,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.SeasonID,
		&i.AchievementType,
		&i.Metadata,
		&i.EarnedAt,
	)
	return i, err
}

const getSeasonAchievements = `-- name: GetSeasonAchievements :many
SELECT id, user_id, group_id, season_id, achievement_type, metadata, earned_at FROM achievements
WHERE season_id = $1
ORDER BY earned_at DESC
`

func (q *Queries) GetSeasonAchievements(ctx context.Context, seasonID sql.NullString) ([]Achievement, error) {
	rows, err := q.db.QueryContext(ctx, getSeasonAchievements, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.SeasonID,
			&i.AchievementType,
			&i.Metadata,
			&i.EarnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAchievements = `-- name: GetUserAchievements :many
SELECT id, user_id, group_id, season_id, achievement_type, metadata, earned_at FROM achievements
WHERE user_id = $1 AND group_id = $2
ORDER BY earned_at DESC
`

type GetUserAchievementsParams struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) GetUserAchievements(ctx context.Context, arg GetUserAchievementsParams) ([]Achievement, error) {
	rows, err := q.db.QueryContext(ctx, getUserAchievements, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.SeasonID,
			&i.AchievementType,
			&i.Metadata,
			&i.EarnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
