// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countActiveUsers30Days = `-- name: CountActiveUsers30Days :one
SELECT count(DISTINCT user_id) FROM group_members
WHERE joined_at > NOW() - INTERVAL '30 days'
`

func (q *Queries) CountActiveUsers30Days(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUsers30Days)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveUsers7Days = `-- name: CountActiveUsers7Days :one
SELECT count(DISTINCT user_id) FROM group_members
WHERE joined_at > NOW() - INTERVAL '7 days'
`

func (q *Queries) CountActiveUsers7Days(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUsers7Days)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroups = `-- name: CountGroups :one
SELECT count(*) FROM groups
`

func (q *Queries) CountGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReports = `-- name: CountReports :one
SELECT count(*) FROM reports
`

func (q *Queries) CountReports(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReports)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT r.id, r.question_id, r.reporter_id, r.reason, r.created_at,
       q.text AS question_text, q.status AS question_status
FROM reports r
JOIN questions q ON q.id = r.question_id
WHERE r.id = $1
`

type GetReportByIDRow struct {
	ID             string         `json:"id"`
	QuestionID     string         `json:"question_id"`
	ReporterID     string         `json:"reporter_id"`
	Reason         sql.NullString `json:"reason"`
	CreatedAt      time.Time      `json:"created_at"`
	QuestionText   string         `json:"question_text"`
	QuestionStatus QuestionStatus `json:"question_status"`
}

func (q *Queries) GetReportByID(ctx context.Context, id string) (GetReportByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReportByID, id)
	var i GetReportByIDRow
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.ReporterID,
		&i.Reason,
		&i.CreatedAt,
		&i.QuestionText,
		&i.QuestionStatus,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT r.id, r.question_id, r.reporter_id, r.reason, r.created_at,
       q.text AS question_text, q.category AS question_category, q.status AS question_status,
       u.username AS reporter_username
FROM reports r
JOIN questions q ON q.id = r.question_id
JOIN users u ON u.id = r.reporter_id
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListReportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListReportsRow struct {
	ID               string           `json:"id"`
	QuestionID       string           `json:"question_id"`
	ReporterID       string           `json:"reporter_id"`
	Reason           sql.NullString   `json:"reason"`
	CreatedAt        time.Time        `json:"created_at"`
	QuestionText     string           `json:"question_text"`
	QuestionCategory QuestionCategory `json:"question_category"`
	QuestionStatus   QuestionStatus   `json:"question_status"`
	ReporterUsername string           `json:"reporter_username"`
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]ListReportsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportsRow{}
	for rows.Next() {
		var i ListReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.ReporterID,
			&i.Reason,
			&i.CreatedAt,
			&i.QuestionText,
			&i.QuestionCategory,
			&i.QuestionStatus,
			&i.ReporterUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumRevenue7Days = `-- name: SumRevenue7Days :one
SELECT COALESCE(SUM(delta), 0)::bigint FROM crystal_logs
WHERE type = 'PURCHASE' AND created_at > NOW() - INTERVAL '7 days'
`

func (q *Queries) SumRevenue7Days(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumRevenue7Days)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
