// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: card_cache.sql

package db

import (
	"context"
)

const getCardCache = `-- name: GetCardCache :one
SELECT id, user_id, season_id, image_url, created_at FROM card_cache WHERE user_id = $1 AND season_id = $2
`

type GetCardCacheParams struct {
	UserID   string `json:"user_id"`
	SeasonID string `json:"season_id"`
}

func (q *Queries) GetCardCache(ctx context.Context, arg GetCardCacheParams) (CardCache, error) {
	row := q.db.QueryRowContext(ctx, getCardCache, arg.UserID, arg.SeasonID)
	var i CardCache
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeasonID,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCardCache = `-- name: UpsertCardCache :one
INSERT INTO card_cache (id, user_id, season_id, image_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, season_id) DO UPDATE SET image_url = EXCLUDED.image_url
RETURNING id, user_id, season_id, image_url, created_at
`

type UpsertCardCacheParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	SeasonID string `json:"season_id"`
	ImageUrl string `json:"image_url"`
}

func (q *Queries) UpsertCardCache(ctx context.Context, arg UpsertCardCacheParams) (CardCache, error) {
	row := q.db.QueryRowContext(ctx, upsertCardCache,
		arg.ID,
		arg.UserID,
		arg.SeasonID,
		arg.ImageUrl,
	)
	var i CardCache
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeasonID,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}
