// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crystal_logs.sql

package db

import (
	"context"
	"database/sql"
)

const createCrystalLog = `-- name: CreateCrystalLog :one
INSERT INTO crystal_logs (id, user_id, delta, balance, type, description, external_id)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, delta, balance, type, description, external_id, created_at
`

type CreateCrystalLogParams struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	Delta       int32          `json:"delta"`
	Balance     int32          `json:"balance"`
	Type        CrystalLogType `json:"type"`
	Description sql.NullString `json:"description"`
	ExternalID  sql.NullString `json:"external_id"`
}

func (q *Queries) CreateCrystalLog(ctx context.Context, arg CreateCrystalLogParams) (CrystalLog, error) {
	row := q.db.QueryRowContext(ctx, createCrystalLog,
		arg.ID,
		arg.UserID,
		arg.Delta,
		arg.Balance,
		arg.Type,
		arg.Description,
		arg.ExternalID,
	)
	var i CrystalLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Delta,
		&i.Balance,
		&i.Type,
		&i.Description,
		&i.ExternalID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBalance = `-- name: GetUserBalance :one
SELECT COALESCE(SUM(delta), 0)::int AS balance FROM crystal_logs WHERE user_id = $1
`

func (q *Queries) GetUserBalance(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserBalance, userID)
	var balance int32
	err := row.Scan(&balance)
	return balance, err
}

const getUserCrystalLogs = `-- name: GetUserCrystalLogs :many
SELECT id, user_id, delta, balance, type, description, external_id, created_at FROM crystal_logs WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetUserCrystalLogsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetUserCrystalLogs(ctx context.Context, arg GetUserCrystalLogsParams) ([]CrystalLog, error) {
	rows, err := q.db.QueryContext(ctx, getUserCrystalLogs, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CrystalLog{}
	for rows.Next() {
		var i CrystalLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Delta,
			&i.Balance,
			&i.Type,
			&i.Description,
			&i.ExternalID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForUpdate = `-- name: LockUserForUpdate :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUserForUpdate(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, lockUserForUpdate, id)
	err := row.Scan(&id)
	return id, err
}
