// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: detector_hints.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countDetectorHints = `-- name: CountDetectorHints :one
SELECT COUNT(*)::bigint FROM detector_hints WHERE user_id = $1 AND season_id = $2
`

type CountDetectorHintsParams struct {
	UserID   string `json:"user_id"`
	SeasonID string `json:"season_id"`
}

func (q *Queries) CountDetectorHints(ctx context.Context, arg CountDetectorHintsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDetectorHints, arg.UserID, arg.SeasonID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createDetectorHint = `-- name: CreateDetectorHint :one
INSERT INTO detector_hints (id, user_id, season_id, revealed_user_id)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, season_id, revealed_user_id, created_at
`

type CreateDetectorHintParams struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	SeasonID       string `json:"season_id"`
	RevealedUserID string `json:"revealed_user_id"`
}

func (q *Queries) CreateDetectorHint(ctx context.Context, arg CreateDetectorHintParams) (DetectorHint, error) {
	row := q.db.QueryRowContext(ctx, createDetectorHint,
		arg.ID,
		arg.UserID,
		arg.SeasonID,
		arg.RevealedUserID,
	)
	var i DetectorHint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeasonID,
		&i.RevealedUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getDetectorHints = `-- name: GetDetectorHints :many
SELECT dh.revealed_user_id, u.username, u.avatar_emoji, u.avatar_url, dh.created_at
FROM detector_hints dh
JOIN users u ON u.id = dh.revealed_user_id
WHERE dh.user_id = $1 AND dh.season_id = $2
ORDER BY dh.created_at
`

type GetDetectorHintsParams struct {
	UserID   string `json:"user_id"`
	SeasonID string `json:"season_id"`
}

type GetDetectorHintsRow struct {
	RevealedUserID string         `json:"revealed_user_id"`
	Username       string         `json:"username"`
	AvatarEmoji    sql.NullString `json:"avatar_emoji"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	CreatedAt      time.Time      `json:"created_at"`
}

// Voters already revealed to this member for this season, with just enough of each to show a
// partial identity. Deliberately selects no username: the hint DTO has no field for one.
func (q *Queries) GetDetectorHints(ctx context.Context, arg GetDetectorHintsParams) ([]GetDetectorHintsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDetectorHints, arg.UserID, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDetectorHintsRow{}
	for rows.Next() {
		var i GetDetectorHintsRow
		if err := rows.Scan(
			&i.RevealedUserID,
			&i.Username,
			&i.AvatarEmoji,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickUnrevealedVoter = `-- name: PickUnrevealedVoter :one
SELECT v.id, v.username, v.avatar_emoji, v.avatar_url
FROM (
  SELECT DISTINCT u.id, u.username, u.avatar_emoji, u.avatar_url
  FROM votes vo
  JOIN users u ON u.id = vo.voter_id
  WHERE vo.season_id = $1
    AND vo.voter_id <> $2
    AND NOT EXISTS (
      SELECT 1 FROM detector_hints dh
      WHERE dh.user_id = $2 AND dh.season_id = $1 AND dh.revealed_user_id = u.id
    )
) v
ORDER BY random()
LIMIT 1
`

type PickUnrevealedVoterParams struct {
	SeasonID string `json:"season_id"`
	VoterID  string `json:"voter_id"`
}

type PickUnrevealedVoterRow struct {
	ID          string         `json:"id"`
	Username    string         `json:"username"`
	AvatarEmoji sql.NullString `json:"avatar_emoji"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
}

// A voter of this season who has not yet been revealed to this member, chosen at random.
//
// Random rather than ordered: a fixed order would let a player infer the rule, and ordering by
// anything meaningful (join date, vote time) would leak a second fact beyond identity.
// Postgres rejects ORDER BY random() alongside SELECT DISTINCT, so the de-duplication happens in a
// subquery and the random pick sits outside it.
func (q *Queries) PickUnrevealedVoter(ctx context.Context, arg PickUnrevealedVoterParams) (PickUnrevealedVoterRow, error) {
	row := q.db.QueryRowContext(ctx, pickUnrevealedVoter, arg.SeasonID, arg.VoterID)
	var i PickUnrevealedVoterRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarEmoji,
		&i.AvatarUrl,
	)
	return i, err
}
