// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: detectors.sql

package db

import (
	"context"
)

const createDetector = `-- name: CreateDetector :one
INSERT INTO detectors (id, user_id, season_id, group_id)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, season_id, group_id, created_at
`

type CreateDetectorParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	SeasonID string `json:"season_id"`
	GroupID  string `json:"group_id"`
}

func (q *Queries) CreateDetector(ctx context.Context, arg CreateDetectorParams) (Detector, error) {
	row := q.db.QueryRowContext(ctx, createDetector,
		arg.ID,
		arg.UserID,
		arg.SeasonID,
		arg.GroupID,
	)
	var i Detector
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeasonID,
		&i.GroupID,
		&i.CreatedAt,
	)
	return i, err
}

const getDetector = `-- name: GetDetector :one
SELECT id, user_id, season_id, group_id, created_at FROM detectors WHERE user_id = $1 AND season_id = $2
`

type GetDetectorParams struct {
	UserID   string `json:"user_id"`
	SeasonID string `json:"season_id"`
}

func (q *Queries) GetDetector(ctx context.Context, arg GetDetectorParams) (Detector, error) {
	row := q.db.QueryRowContext(ctx, getDetector, arg.UserID, arg.SeasonID)
	var i Detector
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeasonID,
		&i.GroupID,
		&i.CreatedAt,
	)
	return i, err
}

const hasDetector = `-- name: HasDetector :one
SELECT EXISTS(SELECT 1 FROM detectors WHERE user_id = $1 AND season_id = $2) AS has_detector
`

type HasDetectorParams struct {
	UserID   string `json:"user_id"`
	SeasonID string `json:"season_id"`
}

func (q *Queries) HasDetector(ctx context.Context, arg HasDetectorParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasDetector, arg.UserID, arg.SeasonID)
	var has_detector bool
	err := row.Scan(&has_detector)
	return has_detector, err
}
