// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fcm_tokens.sql

package db

import (
	"context"
)

const deleteFCMToken = `-- name: DeleteFCMToken :exec
DELETE FROM fcm_tokens WHERE token = $1
`

func (q *Queries) DeleteFCMToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteFCMToken, token)
	return err
}

const getUserFCMTokens = `-- name: GetUserFCMTokens :many
SELECT id, user_id, token, platform, created_at FROM fcm_tokens WHERE user_id = $1
`

func (q *Queries) GetUserFCMTokens(ctx context.Context, userID string) ([]FcmToken, error) {
	rows, err := q.db.QueryContext(ctx, getUserFCMTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FcmToken{}
	for rows.Next() {
		var i FcmToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFCMToken = `-- name: UpsertFCMToken :one
INSERT INTO fcm_tokens (id, user_id, token, platform)
VALUES ($1, $2, $3, $4)
ON CONFLICT (token) DO UPDATE SET user_id = EXCLUDED.user_id, platform = EXCLUDED.platform
RETURNING id, user_id, token, platform, created_at
`

type UpsertFCMTokenParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	Token    string `json:"token"`
	Platform string `json:"platform"`
}

func (q *Queries) UpsertFCMToken(ctx context.Context, arg UpsertFCMTokenParams) (FcmToken, error) {
	row := q.db.QueryRowContext(ctx, upsertFCMToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.Platform,
	)
	var i FcmToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
	)
	return i, err
}
