// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
	"database/sql"
)

const addGroupMember = `-- name: AddGroupMember :one
INSERT INTO group_members (id, user_id, group_id)
VALUES ($1, $2, $3) RETURNING id, user_id, group_id, joined_at
`

type AddGroupMemberParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRowContext(ctx, addGroupMember, arg.ID, arg.UserID, arg.GroupID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.JoinedAt,
	)
	return i, err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT COUNT(*) FROM group_members WHERE group_id = $1
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserGroups = `-- name: CountUserGroups :one
SELECT COUNT(*) FROM group_members WHERE user_id = $1
`

func (q *Queries) CountUserGroups(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserGroups, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, invite_code, admin_id, telegram_chat_username)
VALUES ($1, $2, $3, $4, $5) RETURNING id, name, invite_code, admin_id, telegram_chat_id, telegram_chat_username, telegram_connect_code, telegram_connect_expiry, created_at
`

type CreateGroupParams struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	InviteCode           string         `json:"invite_code"`
	AdminID              string         `json:"admin_id"`
	TelegramChatUsername sql.NullString `json:"telegram_chat_username"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.InviteCode,
		arg.AdminID,
		arg.TelegramChatUsername,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.AdminID,
		&i.TelegramChatID,
		&i.TelegramChatUsername,
		&i.TelegramConnectCode,
		&i.TelegramConnectExpiry,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, invite_code, admin_id, telegram_chat_id, telegram_chat_username, telegram_connect_code, telegram_connect_expiry, created_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.AdminID,
		&i.TelegramChatID,
		&i.TelegramChatUsername,
		&i.TelegramConnectCode,
		&i.TelegramConnectExpiry,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByInviteCode = `-- name: GetGroupByInviteCode :one
SELECT id, name, invite_code, admin_id, telegram_chat_id, telegram_chat_username, telegram_connect_code, telegram_connect_expiry, created_at FROM groups WHERE invite_code = $1
`

func (q *Queries) GetGroupByInviteCode(ctx context.Context, inviteCode string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByInviteCode, inviteCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.AdminID,
		&i.TelegramChatID,
		&i.TelegramChatUsername,
		&i.TelegramConnectCode,
		&i.TelegramConnectExpiry,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByTelegramChatID = `-- name: GetGroupByTelegramChatID :one
SELECT id, name, invite_code, admin_id, telegram_chat_id, telegram_chat_username, telegram_connect_code, telegram_connect_expiry, created_at FROM groups WHERE telegram_chat_id = $1
`

func (q *Queries) GetGroupByTelegramChatID(ctx context.Context, telegramChatID sql.NullString) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByTelegramChatID, telegramChatID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.AdminID,
		&i.TelegramChatID,
		&i.TelegramChatUsername,
		&i.TelegramConnectCode,
		&i.TelegramConnectExpiry,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT u.id, u.username, u.avatar_emoji, u.avatar_url
FROM users u
JOIN group_members gm ON gm.user_id = u.id
WHERE gm.group_id = $1
ORDER BY gm.joined_at ASC
`

type GetGroupMembersRow struct {
	ID          string         `json:"id"`
	Username    string         `json:"username"`
	AvatarEmoji sql.NullString `json:"avatar_emoji"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID string) ([]GetGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupMembersRow{}
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarEmoji,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT g.id, g.name, g.invite_code, g.admin_id, g.telegram_chat_id, g.telegram_chat_username, g.telegram_connect_code, g.telegram_connect_expiry, g.created_at FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
ORDER BY gm.joined_at DESC
`

func (q *Queries) GetUserGroups(ctx context.Context, userID string) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.AdminID,
			&i.TelegramChatID,
			&i.TelegramChatUsername,
			&i.TelegramConnectCode,
			&i.TelegramConnectExpiry,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGroupConnectCode = `-- name: SetGroupConnectCode :exec
UPDATE groups SET telegram_connect_code = $2, telegram_connect_expiry = $3 WHERE id = $1
`

type SetGroupConnectCodeParams struct {
	ID                    string         `json:"id"`
	TelegramConnectCode   sql.NullString `json:"telegram_connect_code"`
	TelegramConnectExpiry sql.NullTime   `json:"telegram_connect_expiry"`
}

func (q *Queries) SetGroupConnectCode(ctx context.Context, arg SetGroupConnectCodeParams) error {
	_, err := q.db.ExecContext(ctx, setGroupConnectCode, arg.ID, arg.TelegramConnectCode, arg.TelegramConnectExpiry)
	return err
}

const updateGroupTelegram = `-- name: UpdateGroupTelegram :exec
UPDATE groups SET telegram_chat_id = $2, telegram_chat_username = $3,
  telegram_connect_code = NULL, telegram_connect_expiry = NULL WHERE id = $1
`

type UpdateGroupTelegramParams struct {
	ID                   string         `json:"id"`
	TelegramChatID       sql.NullString `json:"telegram_chat_id"`
	TelegramChatUsername sql.NullString `json:"telegram_chat_username"`
}

func (q *Queries) UpdateGroupTelegram(ctx context.Context, arg UpdateGroupTelegramParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupTelegram, arg.ID, arg.TelegramChatID, arg.TelegramChatUsername)
	return err
}
