// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const addGroupMember = `-- name: AddGroupMember :one
INSERT INTO group_members (id, user_id, group_id)
VALUES ($1, $2, $3) RETURNING id, user_id, group_id, joined_at
`

type AddGroupMemberParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRowContext(ctx, addGroupMember, arg.ID, arg.UserID, arg.GroupID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.JoinedAt,
	)
	return i, err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT COUNT(*) FROM group_members WHERE group_id = $1
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembersJoinedAfterUser = `-- name: CountMembersJoinedAfterUser :one
SELECT COUNT(*) FROM group_members gm
WHERE gm.group_id = $1 AND gm.joined_at > (
  SELECT gm2.joined_at FROM group_members gm2 WHERE gm2.user_id = $2 AND gm2.group_id = $1
)
`

type CountMembersJoinedAfterUserParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) CountMembersJoinedAfterUser(ctx context.Context, arg CountMembersJoinedAfterUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMembersJoinedAfterUser, arg.GroupID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserGroups = `-- name: CountUserGroups :one
SELECT COUNT(*) FROM group_members WHERE user_id = $1
`

func (q *Queries) CountUserGroups(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserGroups, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, invite_code, admin_id, telegram_chat_username, categories)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, name, invite_code, admin_id, telegram_chat_id, telegram_chat_username, telegram_connect_code, telegram_connect_expiry, created_at, categories
`

type CreateGroupParams struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	InviteCode           string         `json:"invite_code"`
	AdminID              string         `json:"admin_id"`
	TelegramChatUsername sql.NullString `json:"telegram_chat_username"`
	Categories           []string       `json:"categories"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.InviteCode,
		arg.AdminID,
		arg.TelegramChatUsername,
		pq.Array(arg.Categories),
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.AdminID,
		&i.TelegramChatID,
		&i.TelegramChatUsername,
		&i.TelegramConnectCode,
		&i.TelegramConnectExpiry,
		&i.CreatedAt,
		pq.Array(&i.Categories),
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const disconnectTelegramByChat = `-- name: DisconnectTelegramByChat :exec
UPDATE groups SET telegram_chat_id = NULL, telegram_chat_username = NULL
WHERE telegram_chat_id = $1
`

func (q *Queries) DisconnectTelegramByChat(ctx context.Context, telegramChatID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, disconnectTelegramByChat, telegramChatID)
	return err
}

const getAdminUsername = `-- name: GetAdminUsername :one
SELECT username FROM users WHERE id = $1
`

func (q *Queries) GetAdminUsername(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAdminUsername, id)
	var username string
	err := row.Scan(&username)
	return username, err
}

const getGroupByConnectCode = `-- name: GetGroupByConnectCode :one
SELECT id, name, invite_code, admin_id, telegram_chat_id, telegram_chat_username, telegram_connect_code, telegram_connect_expiry, created_at, categories FROM groups WHERE telegram_connect_code = $1 AND telegram_connect_expiry > NOW()
`

func (q *Queries) GetGroupByConnectCode(ctx context.Context, telegramConnectCode sql.NullString) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByConnectCode, telegramConnectCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.AdminID,
		&i.TelegramChatID,
		&i.TelegramChatUsername,
		&i.TelegramConnectCode,
		&i.TelegramConnectExpiry,
		&i.CreatedAt,
		pq.Array(&i.Categories),
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, invite_code, admin_id, telegram_chat_id, telegram_chat_username, telegram_connect_code, telegram_connect_expiry, created_at, categories FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.AdminID,
		&i.TelegramChatID,
		&i.TelegramChatUsername,
		&i.TelegramConnectCode,
		&i.TelegramConnectExpiry,
		&i.CreatedAt,
		pq.Array(&i.Categories),
	)
	return i, err
}

const getGroupByInviteCode = `-- name: GetGroupByInviteCode :one
SELECT id, name, invite_code, admin_id, telegram_chat_id, telegram_chat_username, telegram_connect_code, telegram_connect_expiry, created_at, categories FROM groups WHERE invite_code = $1
`

func (q *Queries) GetGroupByInviteCode(ctx context.Context, inviteCode string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByInviteCode, inviteCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.AdminID,
		&i.TelegramChatID,
		&i.TelegramChatUsername,
		&i.TelegramConnectCode,
		&i.TelegramConnectExpiry,
		&i.CreatedAt,
		pq.Array(&i.Categories),
	)
	return i, err
}

const getGroupByTelegramChatID = `-- name: GetGroupByTelegramChatID :one
SELECT id, name, invite_code, admin_id, telegram_chat_id, telegram_chat_username, telegram_connect_code, telegram_connect_expiry, created_at, categories FROM groups WHERE telegram_chat_id = $1
`

func (q *Queries) GetGroupByTelegramChatID(ctx context.Context, telegramChatID sql.NullString) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByTelegramChatID, telegramChatID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InviteCode,
		&i.AdminID,
		&i.TelegramChatID,
		&i.TelegramChatUsername,
		&i.TelegramConnectCode,
		&i.TelegramConnectExpiry,
		&i.CreatedAt,
		pq.Array(&i.Categories),
	)
	return i, err
}

const getGroupMemberIDs = `-- name: GetGroupMemberIDs :many
SELECT user_id FROM group_members WHERE group_id = $1
`

func (q *Queries) GetGroupMemberIDs(ctx context.Context, groupID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMemberIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT u.id, u.username, u.avatar_emoji, u.avatar_url
FROM users u
JOIN group_members gm ON gm.user_id = u.id
WHERE gm.group_id = $1
ORDER BY gm.joined_at ASC
`

type GetGroupMembersRow struct {
	ID          string         `json:"id"`
	Username    string         `json:"username"`
	AvatarEmoji sql.NullString `json:"avatar_emoji"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID string) ([]GetGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupMembersRow{}
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarEmoji,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextAdmin = `-- name: GetNextAdmin :one
SELECT u.id FROM users u
JOIN group_members gm ON gm.user_id = u.id
WHERE gm.group_id = $1 AND u.id != $2
ORDER BY gm.joined_at ASC
LIMIT 1
`

type GetNextAdminParams struct {
	GroupID string `json:"group_id"`
	ID      string `json:"id"`
}

func (q *Queries) GetNextAdmin(ctx context.Context, arg GetNextAdminParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getNextAdmin, arg.GroupID, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT g.id, g.name, g.invite_code, g.admin_id, g.telegram_chat_id, g.telegram_chat_username, g.telegram_connect_code, g.telegram_connect_expiry, g.created_at, g.categories FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
ORDER BY gm.joined_at DESC
`

func (q *Queries) GetUserGroups(ctx context.Context, userID string) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.AdminID,
			&i.TelegramChatID,
			&i.TelegramChatUsername,
			&i.TelegramConnectCode,
			&i.TelegramConnectExpiry,
			&i.CreatedAt,
			pq.Array(&i.Categories),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroupsWithStats = `-- name: GetUserGroupsWithStats :many
SELECT g.id, g.name, g.invite_code, g.admin_id, g.telegram_chat_id, g.telegram_chat_username, g.telegram_connect_code, g.telegram_connect_expiry, g.created_at, g.categories,
  (SELECT COUNT(*) FROM group_members gm2 WHERE gm2.group_id = g.id) as member_count,
  s.id as active_season_id,
  s.number as active_season_number,
  s.status as active_season_status,
  s.starts_at as active_season_starts_at,
  s.reveal_at as active_season_reveal_at,
  s.ends_at as active_season_ends_at,
  COALESCE((SELECT COUNT(DISTINCT v.voter_id) FROM votes v WHERE v.season_id = s.id), 0)::bigint as voted_count,
  COALESCE((SELECT COUNT(*) FROM votes v WHERE v.season_id = s.id AND v.voter_id = $1), 0)::bigint as user_vote_count
FROM groups g
JOIN group_members gm ON gm.group_id = g.id
LEFT JOIN seasons s ON s.group_id = g.id AND s.status = 'VOTING'
WHERE gm.user_id = $1
ORDER BY gm.joined_at DESC
`

type GetUserGroupsWithStatsRow struct {
	ID                    string           `json:"id"`
	Name                  string           `json:"name"`
	InviteCode            string           `json:"invite_code"`
	AdminID               string           `json:"admin_id"`
	TelegramChatID        sql.NullString   `json:"telegram_chat_id"`
	TelegramChatUsername  sql.NullString   `json:"telegram_chat_username"`
	TelegramConnectCode   sql.NullString   `json:"telegram_connect_code"`
	TelegramConnectExpiry sql.NullTime     `json:"telegram_connect_expiry"`
	CreatedAt             time.Time        `json:"created_at"`
	Categories            []string         `json:"categories"`
	MemberCount           int64            `json:"member_count"`
	ActiveSeasonID        sql.NullString   `json:"active_season_id"`
	ActiveSeasonNumber    sql.NullInt32    `json:"active_season_number"`
	ActiveSeasonStatus    NullSeasonStatus `json:"active_season_status"`
	ActiveSeasonStartsAt  sql.NullTime     `json:"active_season_starts_at"`
	ActiveSeasonRevealAt  sql.NullTime     `json:"active_season_reveal_at"`
	ActiveSeasonEndsAt    sql.NullTime     `json:"active_season_ends_at"`
	VotedCount            int64            `json:"voted_count"`
	UserVoteCount         int64            `json:"user_vote_count"`
}

func (q *Queries) GetUserGroupsWithStats(ctx context.Context, voterID string) ([]GetUserGroupsWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserGroupsWithStats, voterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserGroupsWithStatsRow{}
	for rows.Next() {
		var i GetUserGroupsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.AdminID,
			&i.TelegramChatID,
			&i.TelegramChatUsername,
			&i.TelegramConnectCode,
			&i.TelegramConnectExpiry,
			&i.CreatedAt,
			pq.Array(&i.Categories),
			&i.MemberCount,
			&i.ActiveSeasonID,
			&i.ActiveSeasonNumber,
			&i.ActiveSeasonStatus,
			&i.ActiveSeasonStartsAt,
			&i.ActiveSeasonRevealAt,
			&i.ActiveSeasonEndsAt,
			&i.VotedCount,
			&i.UserVoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isGroupMember = `-- name: IsGroupMember :one
SELECT COUNT(*) FROM group_members WHERE user_id = $1 AND group_id = $2
`

type IsGroupMemberParams struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isGroupMember, arg.UserID, arg.GroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE user_id = $1 AND group_id = $2
`

type RemoveGroupMemberParams struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupMember, arg.UserID, arg.GroupID)
	return err
}

const setGroupConnectCode = `-- name: SetGroupConnectCode :exec
UPDATE groups SET telegram_connect_code = $2, telegram_connect_expiry = $3 WHERE id = $1
`

type SetGroupConnectCodeParams struct {
	ID                    string         `json:"id"`
	TelegramConnectCode   sql.NullString `json:"telegram_connect_code"`
	TelegramConnectExpiry sql.NullTime   `json:"telegram_connect_expiry"`
}

func (q *Queries) SetGroupConnectCode(ctx context.Context, arg SetGroupConnectCodeParams) error {
	_, err := q.db.ExecContext(ctx, setGroupConnectCode, arg.ID, arg.TelegramConnectCode, arg.TelegramConnectExpiry)
	return err
}

const updateGroupAdmin = `-- name: UpdateGroupAdmin :exec
UPDATE groups SET admin_id = $2 WHERE id = $1
`

type UpdateGroupAdminParams struct {
	ID      string `json:"id"`
	AdminID string `json:"admin_id"`
}

func (q *Queries) UpdateGroupAdmin(ctx context.Context, arg UpdateGroupAdminParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupAdmin, arg.ID, arg.AdminID)
	return err
}

const updateGroupInviteCode = `-- name: UpdateGroupInviteCode :exec
UPDATE groups SET invite_code = $2 WHERE id = $1
`

type UpdateGroupInviteCodeParams struct {
	ID         string `json:"id"`
	InviteCode string `json:"invite_code"`
}

func (q *Queries) UpdateGroupInviteCode(ctx context.Context, arg UpdateGroupInviteCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupInviteCode, arg.ID, arg.InviteCode)
	return err
}

const updateGroupName = `-- name: UpdateGroupName :exec
UPDATE groups SET name = $2 WHERE id = $1
`

type UpdateGroupNameParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupName, arg.ID, arg.Name)
	return err
}

const updateGroupTelegram = `-- name: UpdateGroupTelegram :exec
UPDATE groups SET telegram_chat_id = $2, telegram_chat_username = $3,
  telegram_connect_code = NULL, telegram_connect_expiry = NULL WHERE id = $1
`

type UpdateGroupTelegramParams struct {
	ID                   string         `json:"id"`
	TelegramChatID       sql.NullString `json:"telegram_chat_id"`
	TelegramChatUsername sql.NullString `json:"telegram_chat_username"`
}

func (q *Queries) UpdateGroupTelegram(ctx context.Context, arg UpdateGroupTelegramParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupTelegram, arg.ID, arg.TelegramChatID, arg.TelegramChatUsername)
	return err
}

const updateGroupTelegramUsername = `-- name: UpdateGroupTelegramUsername :exec
UPDATE groups SET telegram_chat_username = $2 WHERE id = $1
`

type UpdateGroupTelegramUsernameParams struct {
	ID                   string         `json:"id"`
	TelegramChatUsername sql.NullString `json:"telegram_chat_username"`
}

func (q *Queries) UpdateGroupTelegramUsername(ctx context.Context, arg UpdateGroupTelegramUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupTelegramUsername, arg.ID, arg.TelegramChatUsername)
	return err
}
