// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: next_season_votes.sql

package db

import (
	"context"
	"time"
)

const countNextSeasonVotesByQuestion = `-- name: CountNextSeasonVotesByQuestion :many
SELECT question_id, COUNT(*) as vote_count
FROM next_season_votes
WHERE group_id = $1 AND season_number = $2
GROUP BY question_id
ORDER BY vote_count DESC
`

type CountNextSeasonVotesByQuestionParams struct {
	GroupID      string `json:"group_id"`
	SeasonNumber int32  `json:"season_number"`
}

type CountNextSeasonVotesByQuestionRow struct {
	QuestionID string `json:"question_id"`
	VoteCount  int64  `json:"vote_count"`
}

func (q *Queries) CountNextSeasonVotesByQuestion(ctx context.Context, arg CountNextSeasonVotesByQuestionParams) ([]CountNextSeasonVotesByQuestionRow, error) {
	rows, err := q.db.QueryContext(ctx, countNextSeasonVotesByQuestion, arg.GroupID, arg.SeasonNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountNextSeasonVotesByQuestionRow{}
	for rows.Next() {
		var i CountNextSeasonVotesByQuestionRow
		if err := rows.Scan(&i.QuestionID, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNextSeasonVote = `-- name: CreateNextSeasonVote :one
INSERT INTO next_season_votes (id, group_id, user_id, question_id, season_number)
VALUES ($1, $2, $3, $4, $5) RETURNING id, group_id, user_id, question_id, season_number, created_at
`

type CreateNextSeasonVoteParams struct {
	ID           string `json:"id"`
	GroupID      string `json:"group_id"`
	UserID       string `json:"user_id"`
	QuestionID   string `json:"question_id"`
	SeasonNumber int32  `json:"season_number"`
}

func (q *Queries) CreateNextSeasonVote(ctx context.Context, arg CreateNextSeasonVoteParams) (NextSeasonVote, error) {
	row := q.db.QueryRowContext(ctx, createNextSeasonVote,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.QuestionID,
		arg.SeasonNumber,
	)
	var i NextSeasonVote
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.QuestionID,
		&i.SeasonNumber,
		&i.CreatedAt,
	)
	return i, err
}

const getNextSeasonVotes = `-- name: GetNextSeasonVotes :many
SELECT nsv.id, nsv.group_id, nsv.user_id, nsv.question_id, nsv.season_number, nsv.created_at, q.text as question_text, q.category as question_category
FROM next_season_votes nsv
JOIN questions q ON q.id = nsv.question_id
WHERE nsv.group_id = $1 AND nsv.season_number = $2
ORDER BY nsv.created_at DESC
`

type GetNextSeasonVotesParams struct {
	GroupID      string `json:"group_id"`
	SeasonNumber int32  `json:"season_number"`
}

type GetNextSeasonVotesRow struct {
	ID               string           `json:"id"`
	GroupID          string           `json:"group_id"`
	UserID           string           `json:"user_id"`
	QuestionID       string           `json:"question_id"`
	SeasonNumber     int32            `json:"season_number"`
	CreatedAt        time.Time        `json:"created_at"`
	QuestionText     string           `json:"question_text"`
	QuestionCategory QuestionCategory `json:"question_category"`
}

func (q *Queries) GetNextSeasonVotes(ctx context.Context, arg GetNextSeasonVotesParams) ([]GetNextSeasonVotesRow, error) {
	rows, err := q.db.QueryContext(ctx, getNextSeasonVotes, arg.GroupID, arg.SeasonNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNextSeasonVotesRow{}
	for rows.Next() {
		var i GetNextSeasonVotesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.QuestionID,
			&i.SeasonNumber,
			&i.CreatedAt,
			&i.QuestionText,
			&i.QuestionCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
