// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getTopAttributeAllTime = `-- name: GetTopAttributeAllTime :one
SELECT q.text as question_text, COALESCE(MAX(sr.percentage), 0)::float as percentage
FROM season_results sr
JOIN questions q ON q.id = sr.question_id
JOIN seasons s ON s.id = sr.season_id
WHERE sr.target_id = $1 AND s.group_id = $2 AND s.status = 'REVEALED'
GROUP BY q.id, q.text
ORDER BY MAX(sr.percentage) DESC
LIMIT 1
`

type GetTopAttributeAllTimeParams struct {
	TargetID string `json:"target_id"`
	GroupID  string `json:"group_id"`
}

type GetTopAttributeAllTimeRow struct {
	QuestionText string  `json:"question_text"`
	Percentage   float64 `json:"percentage"`
}

func (q *Queries) GetTopAttributeAllTime(ctx context.Context, arg GetTopAttributeAllTimeParams) (GetTopAttributeAllTimeRow, error) {
	row := q.db.QueryRowContext(ctx, getTopAttributeAllTime, arg.TargetID, arg.GroupID)
	var i GetTopAttributeAllTimeRow
	err := row.Scan(&i.QuestionText, &i.Percentage)
	return i, err
}

const getUserProfileInfo = `-- name: GetUserProfileInfo :one
SELECT id, username, avatar_emoji, avatar_url FROM users WHERE id = $1
`

type GetUserProfileInfoRow struct {
	ID          string         `json:"id"`
	Username    string         `json:"username"`
	AvatarEmoji sql.NullString `json:"avatar_emoji"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
}

func (q *Queries) GetUserProfileInfo(ctx context.Context, id string) (GetUserProfileInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProfileInfo, id)
	var i GetUserProfileInfoRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarEmoji,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserSeasonHistory = `-- name: GetUserSeasonHistory :many
SELECT h.season_id, h.season_number, h.reveal_at,
  h.question_id, h.question_text, h.question_category,
  h.percentage, h.vote_count, h.total_voters
FROM (
  SELECT DISTINCT ON (s.id) s.id as season_id, s.number as season_number, s.reveal_at,
    sr.question_id, q.text as question_text, q.category as question_category,
    sr.percentage, sr.vote_count, sr.total_voters
  FROM seasons s
  JOIN season_results sr ON sr.season_id = s.id AND sr.target_id = $1
  JOIN questions q ON q.id = sr.question_id
  WHERE s.group_id = $2 AND s.status = 'REVEALED'
  ORDER BY s.id, sr.percentage DESC, sr.vote_count DESC
) h
ORDER BY h.season_number DESC
LIMIT $3
`

type GetUserSeasonHistoryParams struct {
	TargetID string `json:"target_id"`
	GroupID  string `json:"group_id"`
	Limit    int32  `json:"limit"`
}

type GetUserSeasonHistoryRow struct {
	SeasonID         string           `json:"season_id"`
	SeasonNumber     int32            `json:"season_number"`
	RevealAt         time.Time        `json:"reveal_at"`
	QuestionID       string           `json:"question_id"`
	QuestionText     string           `json:"question_text"`
	QuestionCategory QuestionCategory `json:"question_category"`
	Percentage       float64          `json:"percentage"`
	VoteCount        int32            `json:"vote_count"`
	TotalVoters      int32            `json:"total_voters"`
}

func (q *Queries) GetUserSeasonHistory(ctx context.Context, arg GetUserSeasonHistoryParams) ([]GetUserSeasonHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserSeasonHistory, arg.TargetID, arg.GroupID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserSeasonHistoryRow{}
	for rows.Next() {
		var i GetUserSeasonHistoryRow
		if err := rows.Scan(
			&i.SeasonID,
			&i.SeasonNumber,
			&i.RevealAt,
			&i.QuestionID,
			&i.QuestionText,
			&i.QuestionCategory,
			&i.Percentage,
			&i.VoteCount,
			&i.TotalVoters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
