// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_preferences.sql

package db

import (
	"context"
)

const getUserPushPreferences = `-- name: GetUserPushPreferences :many
SELECT id, user_id, category, enabled FROM push_preferences WHERE user_id = $1
`

func (q *Queries) GetUserPushPreferences(ctx context.Context, userID string) ([]PushPreference, error) {
	rows, err := q.db.QueryContext(ctx, getUserPushPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushPreference{}
	for rows.Next() {
		var i PushPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isPushEnabled = `-- name: IsPushEnabled :one
SELECT COALESCE(
  (SELECT enabled FROM push_preferences WHERE user_id = $1 AND category = $2),
  TRUE
) AS enabled
`

type IsPushEnabledParams struct {
	UserID   string       `json:"user_id"`
	Category PushCategory `json:"category"`
}

func (q *Queries) IsPushEnabled(ctx context.Context, arg IsPushEnabledParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, isPushEnabled, arg.UserID, arg.Category)
	var enabled interface{}
	err := row.Scan(&enabled)
	return enabled, err
}

const upsertPushPreference = `-- name: UpsertPushPreference :one
INSERT INTO push_preferences (id, user_id, category, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, category) DO UPDATE SET enabled = EXCLUDED.enabled
RETURNING id, user_id, category, enabled
`

type UpsertPushPreferenceParams struct {
	ID       string       `json:"id"`
	UserID   string       `json:"user_id"`
	Category PushCategory `json:"category"`
	Enabled  bool         `json:"enabled"`
}

func (q *Queries) UpsertPushPreference(ctx context.Context, arg UpsertPushPreferenceParams) (PushPreference, error) {
	row := q.db.QueryRowContext(ctx, upsertPushPreference,
		arg.ID,
		arg.UserID,
		arg.Category,
		arg.Enabled,
	)
	var i PushPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Enabled,
	)
	return i, err
}
