// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const getAllGroups = `-- name: GetAllGroups :many
SELECT id, name, invite_code, admin_id, telegram_chat_id, telegram_chat_username, telegram_connect_code, telegram_connect_expiry, created_at, categories FROM groups
`

func (q *Queries) GetAllGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.AdminID,
			&i.TelegramChatID,
			&i.TelegramChatUsername,
			&i.TelegramConnectCode,
			&i.TelegramConnectExpiry,
			&i.CreatedAt,
			pq.Array(&i.Categories),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGroupsWithMembers = `-- name: GetAllGroupsWithMembers :many
SELECT g.id, g.name FROM groups g
JOIN group_members gm ON gm.group_id = g.id
GROUP BY g.id, g.name
HAVING COUNT(gm.id) >= 3
`

type GetAllGroupsWithMembersRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetAllGroupsWithMembers(ctx context.Context) ([]GetAllGroupsWithMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroupsWithMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllGroupsWithMembersRow{}
	for rows.Next() {
		var i GetAllGroupsWithMembersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllVotingSeasons = `-- name: GetAllVotingSeasons :many
SELECT id, group_id, number, status, starts_at, reveal_at, ends_at, created_at FROM seasons WHERE status = 'VOTING'
`

func (q *Queries) GetAllVotingSeasons(ctx context.Context) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, getAllVotingSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Number,
			&i.Status,
			&i.StartsAt,
			&i.RevealAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNonVotersByseason = `-- name: GetNonVotersByseason :many
SELECT gm.user_id FROM group_members gm
WHERE gm.group_id = $1
AND gm.user_id NOT IN (
  SELECT DISTINCT voter_id FROM votes WHERE season_id = $2
)
`

type GetNonVotersByseasonParams struct {
	GroupID  string `json:"group_id"`
	SeasonID string `json:"season_id"`
}

func (q *Queries) GetNonVotersByseason(ctx context.Context, arg GetNonVotersByseasonParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getNonVotersByseason, arg.GroupID, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopVotedCategoryBySeason = `-- name: GetTopVotedCategoryBySeason :one
SELECT q.category FROM votes v
JOIN questions q ON q.id = v.question_id
WHERE v.season_id = $1
GROUP BY q.category
ORDER BY COUNT(*) DESC
LIMIT 1
`

func (q *Queries) GetTopVotedCategoryBySeason(ctx context.Context, seasonID string) (QuestionCategory, error) {
	row := q.db.QueryRowContext(ctx, getTopVotedCategoryBySeason, seasonID)
	var category QuestionCategory
	err := row.Scan(&category)
	return category, err
}

const getUsersWithStreakInGroup = `-- name: GetUsersWithStreakInGroup :many
SELECT user_id FROM user_group_stats
WHERE group_id = $1 AND voting_streak >= $2
`

type GetUsersWithStreakInGroupParams struct {
	GroupID      string `json:"group_id"`
	VotingStreak int32  `json:"voting_streak"`
}

func (q *Queries) GetUsersWithStreakInGroup(ctx context.Context, arg GetUsersWithStreakInGroupParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUsersWithStreakInGroup, arg.GroupID, arg.VotingStreak)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVotedUsersBySeason = `-- name: GetVotedUsersBySeason :many
SELECT DISTINCT voter_id as user_id FROM votes WHERE season_id = $1
`

func (q *Queries) GetVotedUsersBySeason(ctx context.Context, seasonID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getVotedUsersBySeason, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
