// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error)
	AddSeasonQuestion(ctx context.Context, arg AddSeasonQuestionParams) (SeasonQuestion, error)
	AggregateVotesByTarget(ctx context.Context, seasonID string) ([]AggregateVotesByTargetRow, error)
	CountActiveUsers30Days(ctx context.Context) (int64, error)
	CountActiveUsers7Days(ctx context.Context) (int64, error)
	// How many members *of this group* the user cannot interact with, in either direction.
	//
	// Scoped to the group on purpose. ListBlockedUserIDs is global, so subtracting its length from a
	// group's membership also subtracts people the user blocked in other groups entirely — which silently
	// shrank one group because of something that happened in another.
	CountBlockedGroupMembers(ctx context.Context, arg CountBlockedGroupMembersParams) (int64, error)
	CountCompletedVoters(ctx context.Context, arg CountCompletedVotersParams) (int64, error)
	CountDetectorHints(ctx context.Context, arg CountDetectorHintsParams) (int64, error)
	CountGroupMembers(ctx context.Context, groupID string) (int64, error)
	CountGroups(ctx context.Context) (int64, error)
	// Memberships grouped by how the member arrived. Compared against CountSharesByChannel to
	// judge the loop from a shared card to a joined member.
	CountJoinsBySource(ctx context.Context) ([]CountJoinsBySourceRow, error)
	// How many non-edgy questions the given categories offer. Used to refuse a combination that would
	// hand a kind-only group an empty season: HOT and SECRETS exist to provoke, so every question in them
	// is edgy and a kind-only group restricted to them would draw nothing.
	//
	// Counted against the bank rather than compared with a hardcoded list of "kind categories", so adding
	// one gentle SECRETS question is enough to make the combination legal — no code change needed.
	CountKindQuestionsByCategories(ctx context.Context, dollar_1 []QuestionCategory) (int64, error)
	CountMembersJoinedAfterUser(ctx context.Context, arg CountMembersJoinedAfterUserParams) (int64, error)
	CountNextSeasonVotesByQuestion(ctx context.Context, arg CountNextSeasonVotesByQuestionParams) ([]CountNextSeasonVotesByQuestionRow, error)
	CountReferralsByUser(ctx context.Context, invitedBy sql.NullString) (int64, error)
	CountReports(ctx context.Context) (int64, error)
	// How many seasons this group has actually revealed. CLOSED counts: see GetGroupChronicle above.
	CountRevealedSeasons(ctx context.Context, groupID string) (int64, error)
	CountSeasonQuestions(ctx context.Context, seasonID string) (int64, error)
	CountSeasonVoters(ctx context.Context, seasonID string) (int64, error)
	// Shares grouped by channel, for the acquisition funnel in admin stats.
	CountSharesByChannel(ctx context.Context) ([]CountSharesByChannelRow, error)
	CountSharesBySeason(ctx context.Context, seasonID string) (int64, error)
	CountUniqueVoters(ctx context.Context, seasonID string) (int64, error)
	CountUserGroups(ctx context.Context, userID string) (int64, error)
	CountUserQuestionsInGroup(ctx context.Context, arg CountUserQuestionsInGroupParams) (int64, error)
	CountUserReports(ctx context.Context) (int64, error)
	// How many distinct members have answered at least one question about this target.
	// Excludes the target's own votes: answering about others must not inflate your own count.
	CountVotersAboutTarget(ctx context.Context, arg CountVotersAboutTargetParams) (int64, error)
	CountVotesCastByUser(ctx context.Context, arg CountVotesCastByUserParams) (int64, error)
	CountVotesReceivedByUser(ctx context.Context, arg CountVotesReceivedByUserParams) (int64, error)
	CreateAchievement(ctx context.Context, arg CreateAchievementParams) (Achievement, error)
	// Idempotent: blocking twice is not an error, and the second call must not fail the request.
	// A no-op update, so the existing row is returned rather than the insert failing.
	CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error)
	CreateCrystalLog(ctx context.Context, arg CreateCrystalLogParams) (CrystalLog, error)
	CreateDetector(ctx context.Context, arg CreateDetectorParams) (Detector, error)
	CreateDetectorHint(ctx context.Context, arg CreateDetectorHintParams) (DetectorHint, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupBan(ctx context.Context, arg CreateGroupBanParams) (GroupBan, error)
	CreateNextSeasonVote(ctx context.Context, arg CreateNextSeasonVoteParams) (NextSeasonVote, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateQuestionSeed(ctx context.Context, arg CreateQuestionSeedParams) error
	CreateReaction(ctx context.Context, arg CreateReactionParams) (Reaction, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error)
	CreateSeasonResult(ctx context.Context, arg CreateSeasonResultParams) (SeasonResult, error)
	CreateShareEvent(ctx context.Context, arg CreateShareEventParams) (ShareEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// One report per person per reporter, matching the shape the question queue already uses.
	CreateUserReport(ctx context.Context, arg CreateUserReportParams) (UserReport, error)
	CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error)
	DeleteBlock(ctx context.Context, arg DeleteBlockParams) error
	DeleteFCMToken(ctx context.Context, token string) error
	DeleteGroup(ctx context.Context, id string) error
	DeleteSeasonResultsBySeason(ctx context.Context, seasonID string) error
	DeleteUser(ctx context.Context, id string) error
	DisconnectTelegramByChat(ctx context.Context, telegramChatID sql.NullString) error
	GetActiveSeasonByGroup(ctx context.Context, groupID string) (Season, error)
	GetAdminUsername(ctx context.Context, id string) (string, error)
	GetAllGroups(ctx context.Context) ([]Group, error)
	GetAllGroupsWithMembers(ctx context.Context) ([]GetAllGroupsWithMembersRow, error)
	// Tone is selected for the same reason as in GetSeasonResultsByUser: this feeds the members-cards
	// list, whose cards are ordered by the same rule as a member's own.
	GetAllSeasonResultsWithUsers(ctx context.Context, seasonID string) ([]GetAllSeasonResultsWithUsersRow, error)
	GetAllVotingSeasons(ctx context.Context) ([]Season, error)
	GetCardCache(ctx context.Context, arg GetCardCacheParams) (CardCache, error)
	GetDetector(ctx context.Context, arg GetDetectorParams) (Detector, error)
	// Voters already revealed to this member for this season, with just enough of each to show a
	// partial identity. Deliberately selects no username: the hint DTO has no field for one.
	GetDetectorHints(ctx context.Context, arg GetDetectorHintsParams) ([]GetDetectorHintsRow, error)
	GetFirstCompletedVoter(ctx context.Context, arg GetFirstCompletedVoterParams) (string, error)
	GetFirstVoteTimeByUser(ctx context.Context, arg GetFirstVoteTimeByUserParams) (time.Time, error)
	GetGroupAllQuestions(ctx context.Context, arg GetGroupAllQuestionsParams) ([]Question, error)
	GetGroupByConnectCode(ctx context.Context, telegramConnectCode sql.NullString) (Group, error)
	GetGroupByID(ctx context.Context, id string) (Group, error)
	// Matches case-insensitively so a code typed in any case resolves, and so legacy UUID codes
	// keep working without a compatibility branch. Uses groups_invite_code_upper_idx.
	GetGroupByInviteCode(ctx context.Context, upper interface{}) (Group, error)
	GetGroupByTelegramChatID(ctx context.Context, telegramChatID sql.NullString) (Group, error)
	// The group's shared record: for each of the last $2 revealed seasons, the standout result per
	// question. Flat rows, grouped into seasons by the service.
	//
	// One query rather than GetTopResultPerQuestion per season: a group that has played for a year has
	// ~50 seasons, and the per-season loop would be the second N+1 in this codebase.
	//
	// total_voters comes along because it decides the anonymity marking: a share of two voters identifies
	// them whatever the group's size was, and the group's historic membership is not recoverable — the
	// group_members table records joined_at and no departure.
	//
	// The season window is a subquery so DISTINCT ON can order by (season, question, percentage) while the
	// window itself is ordered by season number.
	GetGroupChronicle(ctx context.Context, arg GetGroupChronicleParams) ([]GetGroupChronicleRow, error)
	GetGroupCustomQuestions(ctx context.Context, groupID sql.NullString) ([]Question, error)
	// Every current member of the group with their stored guess accuracy.
	//
	// A LEFT JOIN on purpose: a member who has not yet been through a reveal has no stats row, and that is
	// how "not yet ranked" is expressed. Defaulting them to zero would rank them last on a number nobody
	// measured.
	//
	// The accuracy is read, never recomputed: the stored value is a rolling average over a 5-season
	// window (see internal/service/achievements), so recomputing here would show a different number than
	// the profile does.
	GetGroupGuessStanding(ctx context.Context, groupID string) ([]GetGroupGuessStandingRow, error)
	GetGroupMemberIDs(ctx context.Context, groupID string) ([]string, error)
	GetGroupMembers(ctx context.Context, groupID string) ([]GetGroupMembersRow, error)
	GetGroupsNeedingNewSeason(ctx context.Context) ([]Group, error)
	// Safety net for the hourly cron: eligible groups with no open season whose most
	// recent season finished more than an hour ago (so it never races the Sunday cron
	// or the post-kickoff follow-up).
	GetGroupsNeedingSeasonMaintenance(ctx context.Context) ([]Group, error)
	// CLOSED as well as REVEALED, for the same reason as GetPreviousRevealedSeason: the multi-season
	// achievements that read this found no prior seasons and could never fire.
	GetLastNRevealedSeasons(ctx context.Context, arg GetLastNRevealedSeasonsParams) ([]Season, error)
	GetLastSeasonNumber(ctx context.Context, groupID string) (int32, error)
	// The category this target has received the most votes in.
	// Ties break on the category's own ordering — arbitrary but stable, because a random tiebreak would
	// make the Thursday teaser flicker between two emojis on consecutive loads and read as a bug.
	GetLeadingCategoryForTarget(ctx context.Context, arg GetLeadingCategoryForTargetParams) (GetLeadingCategoryForTargetRow, error)
	GetMaxPercentageForUser(ctx context.Context, arg GetMaxPercentageForUserParams) (float64, error)
	GetMembershipByUserAndGroup(ctx context.Context, arg GetMembershipByUserAndGroupParams) (GroupMember, error)
	GetNextAdmin(ctx context.Context, arg GetNextAdminParams) (string, error)
	GetNextSeasonVotes(ctx context.Context, arg GetNextSeasonVotesParams) ([]GetNextSeasonVotesRow, error)
	GetNonVotersByseason(ctx context.Context, arg GetNonVotersByseasonParams) ([]string, error)
	// CLOSED as well as REVEALED. This runs at reveal time, when the current season is the REVEALED one
	// and every earlier season has already been closed by createSeasonForGroup — so filtering on REVEALED
	// alone returned no rows, and the trend line it feeds never rendered.
	GetPreviousRevealedSeason(ctx context.Context, arg GetPreviousRevealedSeasonParams) (Season, error)
	GetQuestionByID(ctx context.Context, id string) (Question, error)
	GetRandomSystemQuestions(ctx context.Context, limit int32) ([]Question, error)
	// $4 is the group's kind_only setting. Filtering inside the query rather than afterwards matters: the
	// LIMIT is min(10, members*2), so dropping rows after it would hand a kind-only group fewer questions
	// than an ordinary one.
	GetRandomSystemQuestionsByCategories(ctx context.Context, arg GetRandomSystemQuestionsByCategoriesParams) ([]Question, error)
	GetReactionsForUser(ctx context.Context, arg GetReactionsForUserParams) ([]GetReactionsForUserRow, error)
	GetReportByID(ctx context.Context, id string) (GetReportByIDRow, error)
	// Deliberately REVEALED only: this is the closing step itself, finding the seasons to mark CLOSED.
	GetRevealedSeasonsForGroup(ctx context.Context, groupID string) ([]Season, error)
	GetSeasonAchievements(ctx context.Context, seasonID sql.NullString) ([]Achievement, error)
	GetSeasonByID(ctx context.Context, id string) (Season, error)
	GetSeasonQuestions(ctx context.Context, seasonID string) ([]Question, error)
	GetSeasonResults(ctx context.Context, seasonID string) ([]SeasonResult, error)
	// Tone comes along because the card's order depends on it: within a near-tie the warmer attribute
	// leads, since the card is the thing a person is invited to share.
	GetSeasonResultsByUser(ctx context.Context, arg GetSeasonResultsByUserParams) ([]GetSeasonResultsByUserRow, error)
	GetSeasonsForReveal(ctx context.Context) ([]Season, error)
	GetSystemQuestionsByCategory(ctx context.Context, category QuestionCategory) ([]Question, error)
	// CLOSED as well as REVEALED: a REVEALED season becomes CLOSED when the next one opens, so a group
	// has at most one REVEALED season and "all time" filtered on REVEALED alone meant "this week".
	GetTopAttributeAllTime(ctx context.Context, arg GetTopAttributeAllTimeParams) (GetTopAttributeAllTimeRow, error)
	GetTopAttributeForUser(ctx context.Context, arg GetTopAttributeForUserParams) (GetTopAttributeForUserRow, error)
	GetTopResultPerQuestion(ctx context.Context, seasonID string) ([]GetTopResultPerQuestionRow, error)
	GetTopVotedCategoryBySeason(ctx context.Context, seasonID string) (QuestionCategory, error)
	GetUserAchievements(ctx context.Context, arg GetUserAchievementsParams) ([]Achievement, error)
	GetUserAchievementsByType(ctx context.Context, arg GetUserAchievementsByTypeParams) ([]Achievement, error)
	GetUserBalance(ctx context.Context, userID string) (int32, error)
	GetUserByAppleID(ctx context.Context, appleID sql.NullString) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByPhone(ctx context.Context, phone sql.NullString) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserCrystalLogs(ctx context.Context, arg GetUserCrystalLogsParams) ([]CrystalLog, error)
	GetUserFCMTokens(ctx context.Context, userID string) ([]FcmToken, error)
	GetUserGroupStats(ctx context.Context, arg GetUserGroupStatsParams) (UserGroupStat, error)
	GetUserGroups(ctx context.Context, userID string) ([]Group, error)
	GetUserGroupsWithStats(ctx context.Context, voterID string) ([]GetUserGroupsWithStatsRow, error)
	GetUserProfileInfo(ctx context.Context, id string) (GetUserProfileInfoRow, error)
	GetUserPushPreferences(ctx context.Context, userID string) ([]PushPreference, error)
	GetUserSeasonHistory(ctx context.Context, arg GetUserSeasonHistoryParams) ([]GetUserSeasonHistoryRow, error)
	GetUsersWithStreakInGroup(ctx context.Context, arg GetUsersWithStreakInGroupParams) ([]string, error)
	GetVotedUsersBySeason(ctx context.Context, seasonID string) ([]string, error)
	GetVoterProfilesBySeason(ctx context.Context, seasonID string) ([]GetVoterProfilesBySeasonRow, error)
	GetVotersBySeason(ctx context.Context, seasonID string) ([]string, error)
	GetVotesBySeasonAndVoter(ctx context.Context, arg GetVotesBySeasonAndVoterParams) ([]Vote, error)
	GetVotesByVoterInSeason(ctx context.Context, arg GetVotesByVoterInSeasonParams) ([]GetVotesByVoterInSeasonRow, error)
	// Members who may be rated by this voter: everyone else, minus anyone blocked in either direction.
	//
	// Done in SQL rather than by filtering GetGroupMembers in Go so the session's target list and the
	// vote endpoint cannot disagree — the bug this prevents is offering a target the vote then refuses.
	GetVotingTargets(ctx context.Context, arg GetVotingTargetsParams) ([]GetVotingTargetsRow, error)
	GetWinnerPerQuestion(ctx context.Context, seasonID string) ([]GetWinnerPerQuestionRow, error)
	HasAchievementInGroup(ctx context.Context, arg HasAchievementInGroupParams) (int64, error)
	HasDetector(ctx context.Context, arg HasDetectorParams) (bool, error)
	HasNextSeasonVote(ctx context.Context, arg HasNextSeasonVoteParams) (int64, error)
	HasQuestionBeenToppedInGroup(ctx context.Context, arg HasQuestionBeenToppedInGroupParams) (int64, error)
	HasUserReported(ctx context.Context, arg HasUserReportedParams) (bool, error)
	HasUserVotedInSeason(ctx context.Context, arg HasUserVotedInSeasonParams) (int64, error)
	HasVoteForQuestion(ctx context.Context, arg HasVoteForQuestionParams) (int64, error)
	HealthCheck(ctx context.Context) (int32, error)
	// A block's effect is symmetric even though only one person created it.
	IsBlockedEitherWay(ctx context.Context, arg IsBlockedEitherWayParams) (bool, error)
	IsGroupBanned(ctx context.Context, arg IsGroupBannedParams) (bool, error)
	IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (int64, error)
	IsPushEnabled(ctx context.Context, arg IsPushEnabledParams) (interface{}, error)
	// Everyone this user cannot interact with, in either direction.
	// One scan with a CASE rather than a UNION of two scans: the UNION form also confuses sqlc's
	// analyzer about which branch an unqualified column belongs to.
	// The cast is needed: without it sqlc cannot infer the CASE expression's type.
	ListBlockedUserIDs(ctx context.Context, blockerID string) ([]string, error)
	ListReports(ctx context.Context, arg ListReportsParams) ([]ListReportsRow, error)
	ListUserReports(ctx context.Context, arg ListUserReportsParams) ([]ListUserReportsRow, error)
	LockUserForUpdate(ctx context.Context, id string) (string, error)
	// A voter of this season who has not yet been revealed to this member, chosen at random.
	//
	// Random rather than ordered: a fixed order would let a player infer the rule, and ordering by
	// anything meaningful (join date, vote time) would leak a second fact beyond identity.
	// Postgres rejects ORDER BY random() alongside SELECT DISTINCT, so the de-duplication happens in a
	// subquery and the random pick sits outside it.
	PickUnrevealedVoter(ctx context.Context, arg PickUnrevealedVoterParams) (PickUnrevealedVoterRow, error)
	PostponeSeason(ctx context.Context, arg PostponeSeasonParams) (Season, error)
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	// Brings a kickoff season's reveal forward. The reveal_at > @reveal_at guard makes
	// this idempotent and keeps later voters from pushing the time back.
	ScheduleKickoffReveal(ctx context.Context, arg ScheduleKickoffRevealParams) (Season, error)
	SetGroupConnectCode(ctx context.Context, arg SetGroupConnectCodeParams) error
	SumRevenue7Days(ctx context.Context) (int64, error)
	UpdateGroupAdmin(ctx context.Context, arg UpdateGroupAdminParams) error
	UpdateGroupInviteCode(ctx context.Context, arg UpdateGroupInviteCodeParams) error
	UpdateGroupKindOnly(ctx context.Context, arg UpdateGroupKindOnlyParams) error
	UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) error
	UpdateGroupTelegram(ctx context.Context, arg UpdateGroupTelegramParams) error
	UpdateGroupTelegramUsername(ctx context.Context, arg UpdateGroupTelegramUsernameParams) error
	UpdateQuestionStatus(ctx context.Context, arg UpdateQuestionStatusParams) error
	UpdateSeasonStatus(ctx context.Context, arg UpdateSeasonStatusParams) error
	UpdateUserAvatarURL(ctx context.Context, arg UpdateUserAvatarURLParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserProfileWithUsername(ctx context.Context, arg UpdateUserProfileWithUsernameParams) (User, error)
	UpsertCardCache(ctx context.Context, arg UpsertCardCacheParams) (CardCache, error)
	UpsertFCMToken(ctx context.Context, arg UpsertFCMTokenParams) (FcmToken, error)
	UpsertPushPreference(ctx context.Context, arg UpsertPushPreferenceParams) (PushPreference, error)
	UpsertUserGroupStats(ctx context.Context, arg UpsertUserGroupStatsParams) (UserGroupStat, error)
}

var _ Querier = (*Queries)(nil)
