// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (id, text, category, source, group_id, author_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, text, category, source, group_id, author_id, status, created_at
`

type CreateQuestionParams struct {
	ID       string           `json:"id"`
	Text     string           `json:"text"`
	Category QuestionCategory `json:"category"`
	Source   QuestionSource   `json:"source"`
	GroupID  sql.NullString   `json:"group_id"`
	AuthorID sql.NullString   `json:"author_id"`
	Status   QuestionStatus   `json:"status"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion,
		arg.ID,
		arg.Text,
		arg.Category,
		arg.Source,
		arg.GroupID,
		arg.AuthorID,
		arg.Status,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Category,
		&i.Source,
		&i.GroupID,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createQuestionSeed = `-- name: CreateQuestionSeed :exec
INSERT INTO questions (id, text, category, source, status)
VALUES ($1, $2, $3, 'SYSTEM', 'ACTIVE')
ON CONFLICT DO NOTHING
`

type CreateQuestionSeedParams struct {
	ID       string           `json:"id"`
	Text     string           `json:"text"`
	Category QuestionCategory `json:"category"`
}

func (q *Queries) CreateQuestionSeed(ctx context.Context, arg CreateQuestionSeedParams) error {
	_, err := q.db.ExecContext(ctx, createQuestionSeed, arg.ID, arg.Text, arg.Category)
	return err
}

const getGroupCustomQuestions = `-- name: GetGroupCustomQuestions :many
SELECT id, text, category, source, group_id, author_id, status, created_at FROM questions
WHERE group_id = $1 AND source = 'USER' AND status = 'ACTIVE'
ORDER BY created_at DESC
`

func (q *Queries) GetGroupCustomQuestions(ctx context.Context, groupID sql.NullString) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getGroupCustomQuestions, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Category,
			&i.Source,
			&i.GroupID,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, text, category, source, group_id, author_id, status, created_at FROM questions WHERE id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id string) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Category,
		&i.Source,
		&i.GroupID,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getRandomSystemQuestions = `-- name: GetRandomSystemQuestions :many
SELECT id, text, category, source, group_id, author_id, status, created_at FROM questions
WHERE source = 'SYSTEM' AND status = 'ACTIVE'
ORDER BY RANDOM()
LIMIT $1
`

func (q *Queries) GetRandomSystemQuestions(ctx context.Context, limit int32) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getRandomSystemQuestions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Category,
			&i.Source,
			&i.GroupID,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomSystemQuestionsByCategories = `-- name: GetRandomSystemQuestionsByCategories :many
SELECT id, text, category, source, group_id, author_id, status, created_at FROM questions
WHERE source = 'SYSTEM' AND status = 'ACTIVE'
  AND category = ANY($1::question_category[])
  AND id NOT IN (
    SELECT sq.question_id FROM season_questions sq
    JOIN seasons s ON s.id = sq.season_id
    WHERE s.group_id = $2
      AND s.number > (SELECT COALESCE(MAX(number), 0) - 3 FROM seasons WHERE group_id = $2)
  )
ORDER BY RANDOM()
LIMIT $3
`

type GetRandomSystemQuestionsByCategoriesParams struct {
	Column1 []QuestionCategory `json:"column_1"`
	GroupID string             `json:"group_id"`
	Limit   int32              `json:"limit"`
}

func (q *Queries) GetRandomSystemQuestionsByCategories(ctx context.Context, arg GetRandomSystemQuestionsByCategoriesParams) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getRandomSystemQuestionsByCategories, pq.Array(arg.Column1), arg.GroupID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Category,
			&i.Source,
			&i.GroupID,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemQuestionsByCategory = `-- name: GetSystemQuestionsByCategory :many
SELECT id, text, category, source, group_id, author_id, status, created_at FROM questions
WHERE source = 'SYSTEM' AND status = 'ACTIVE' AND category = $1
ORDER BY RANDOM()
`

func (q *Queries) GetSystemQuestionsByCategory(ctx context.Context, category QuestionCategory) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getSystemQuestionsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Category,
			&i.Source,
			&i.GroupID,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestionStatus = `-- name: UpdateQuestionStatus :exec
UPDATE questions SET status = $2 WHERE id = $1
`

type UpdateQuestionStatusParams struct {
	ID     string         `json:"id"`
	Status QuestionStatus `json:"status"`
}

func (q *Queries) UpdateQuestionStatus(ctx context.Context, arg UpdateQuestionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateQuestionStatus, arg.ID, arg.Status)
	return err
}
