// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createReaction = `-- name: CreateReaction :one
INSERT INTO reactions (id, season_id, reactor_id, target_id, emoji)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (season_id, reactor_id, target_id) DO UPDATE SET emoji = EXCLUDED.emoji
RETURNING id, season_id, reactor_id, target_id, emoji, created_at
`

type CreateReactionParams struct {
	ID        string `json:"id"`
	SeasonID  string `json:"season_id"`
	ReactorID string `json:"reactor_id"`
	TargetID  string `json:"target_id"`
	Emoji     string `json:"emoji"`
}

func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) (Reaction, error) {
	row := q.db.QueryRowContext(ctx, createReaction,
		arg.ID,
		arg.SeasonID,
		arg.ReactorID,
		arg.TargetID,
		arg.Emoji,
	)
	var i Reaction
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.ReactorID,
		&i.TargetID,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const getReactionsForUser = `-- name: GetReactionsForUser :many
SELECT r.id, r.season_id, r.reactor_id, r.target_id, r.emoji, r.created_at, u.username as reactor_username, u.avatar_emoji as reactor_avatar_emoji
FROM reactions r
JOIN users u ON u.id = r.reactor_id
WHERE r.season_id = $1 AND r.target_id = $2
ORDER BY r.created_at DESC
`

type GetReactionsForUserParams struct {
	SeasonID string `json:"season_id"`
	TargetID string `json:"target_id"`
}

type GetReactionsForUserRow struct {
	ID                 string         `json:"id"`
	SeasonID           string         `json:"season_id"`
	ReactorID          string         `json:"reactor_id"`
	TargetID           string         `json:"target_id"`
	Emoji              string         `json:"emoji"`
	CreatedAt          time.Time      `json:"created_at"`
	ReactorUsername    string         `json:"reactor_username"`
	ReactorAvatarEmoji sql.NullString `json:"reactor_avatar_emoji"`
}

func (q *Queries) GetReactionsForUser(ctx context.Context, arg GetReactionsForUserParams) ([]GetReactionsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getReactionsForUser, arg.SeasonID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReactionsForUserRow{}
	for rows.Next() {
		var i GetReactionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.ReactorID,
			&i.TargetID,
			&i.Emoji,
			&i.CreatedAt,
			&i.ReactorUsername,
			&i.ReactorAvatarEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
