// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"
	"database/sql"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (id, question_id, reporter_id, reason)
VALUES ($1, $2, $3, $4) RETURNING id, question_id, reporter_id, reason, created_at
`

type CreateReportParams struct {
	ID         string         `json:"id"`
	QuestionID string         `json:"question_id"`
	ReporterID string         `json:"reporter_id"`
	Reason     sql.NullString `json:"reason"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.ID,
		arg.QuestionID,
		arg.ReporterID,
		arg.Reason,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.ReporterID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const hasUserReported = `-- name: HasUserReported :one
SELECT EXISTS(SELECT 1 FROM reports WHERE question_id = $1 AND reporter_id = $2) AS has_reported
`

type HasUserReportedParams struct {
	QuestionID string `json:"question_id"`
	ReporterID string `json:"reporter_id"`
}

func (q *Queries) HasUserReported(ctx context.Context, arg HasUserReportedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasUserReported, arg.QuestionID, arg.ReporterID)
	var has_reported bool
	err := row.Scan(&has_reported)
	return has_reported, err
}
