// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: safety.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countBlockedGroupMembers = `-- name: CountBlockedGroupMembers :one
SELECT COUNT(*)::bigint
FROM group_members gm
WHERE gm.group_id = $1
  AND EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $2 AND b.blocked_id = gm.user_id)
       OR (b.blocker_id = gm.user_id AND b.blocked_id = $2)
  )
`

type CountBlockedGroupMembersParams struct {
	GroupID   string `json:"group_id"`
	BlockerID string `json:"blocker_id"`
}

// How many members *of this group* the user cannot interact with, in either direction.
//
// Scoped to the group on purpose. ListBlockedUserIDs is global, so subtracting its length from a
// group's membership also subtracts people the user blocked in other groups entirely — which silently
// shrank one group because of something that happened in another.
func (q *Queries) CountBlockedGroupMembers(ctx context.Context, arg CountBlockedGroupMembersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlockedGroupMembers, arg.GroupID, arg.BlockerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserReports = `-- name: CountUserReports :one
SELECT COUNT(*)::bigint FROM user_reports
`

func (q *Queries) CountUserReports(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserReports)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createBlock = `-- name: CreateBlock :one
INSERT INTO blocks (id, blocker_id, blocked_id)
VALUES ($1, $2, $3)
ON CONFLICT (blocker_id, blocked_id) DO UPDATE SET created_at = blocks.created_at
RETURNING id, blocker_id, blocked_id, created_at
`

type CreateBlockParams struct {
	ID        string `json:"id"`
	BlockerID string `json:"blocker_id"`
	BlockedID string `json:"blocked_id"`
}

// Idempotent: blocking twice is not an error, and the second call must not fail the request.
// A no-op update, so the existing row is returned rather than the insert failing.
func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error) {
	row := q.db.QueryRowContext(ctx, createBlock, arg.ID, arg.BlockerID, arg.BlockedID)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.BlockerID,
		&i.BlockedID,
		&i.CreatedAt,
	)
	return i, err
}

const createGroupBan = `-- name: CreateGroupBan :one
INSERT INTO group_bans (id, group_id, user_id, banned_by, reason)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (group_id, user_id) DO UPDATE SET reason = EXCLUDED.reason
RETURNING id, group_id, user_id, banned_by, reason, created_at
`

type CreateGroupBanParams struct {
	ID       string         `json:"id"`
	GroupID  string         `json:"group_id"`
	UserID   string         `json:"user_id"`
	BannedBy sql.NullString `json:"banned_by"`
	Reason   sql.NullString `json:"reason"`
}

func (q *Queries) CreateGroupBan(ctx context.Context, arg CreateGroupBanParams) (GroupBan, error) {
	row := q.db.QueryRowContext(ctx, createGroupBan,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.BannedBy,
		arg.Reason,
	)
	var i GroupBan
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.BannedBy,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createUserReport = `-- name: CreateUserReport :one
INSERT INTO user_reports (id, reported_id, reporter_id, group_id, reason)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (reported_id, reporter_id) DO UPDATE SET reason = EXCLUDED.reason
RETURNING id, reported_id, reporter_id, group_id, reason, created_at
`

type CreateUserReportParams struct {
	ID         string         `json:"id"`
	ReportedID string         `json:"reported_id"`
	ReporterID string         `json:"reporter_id"`
	GroupID    sql.NullString `json:"group_id"`
	Reason     sql.NullString `json:"reason"`
}

// One report per person per reporter, matching the shape the question queue already uses.
func (q *Queries) CreateUserReport(ctx context.Context, arg CreateUserReportParams) (UserReport, error) {
	row := q.db.QueryRowContext(ctx, createUserReport,
		arg.ID,
		arg.ReportedID,
		arg.ReporterID,
		arg.GroupID,
		arg.Reason,
	)
	var i UserReport
	err := row.Scan(
		&i.ID,
		&i.ReportedID,
		&i.ReporterID,
		&i.GroupID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type DeleteBlockParams struct {
	BlockerID string `json:"blocker_id"`
	BlockedID string `json:"blocked_id"`
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const getVotingTargets = `-- name: GetVotingTargets :many
SELECT u.id, u.username, u.avatar_emoji, u.avatar_url
FROM users u
JOIN group_members gm ON gm.user_id = u.id
WHERE gm.group_id = $1
  AND u.id <> $2
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $2 AND b.blocked_id = u.id)
       OR (b.blocker_id = u.id AND b.blocked_id = $2)
  )
ORDER BY gm.joined_at
`

type GetVotingTargetsParams struct {
	GroupID string `json:"group_id"`
	ID      string `json:"id"`
}

type GetVotingTargetsRow struct {
	ID          string         `json:"id"`
	Username    string         `json:"username"`
	AvatarEmoji sql.NullString `json:"avatar_emoji"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
}

// Members who may be rated by this voter: everyone else, minus anyone blocked in either direction.
//
// Done in SQL rather than by filtering GetGroupMembers in Go so the session's target list and the
// vote endpoint cannot disagree — the bug this prevents is offering a target the vote then refuses.
func (q *Queries) GetVotingTargets(ctx context.Context, arg GetVotingTargetsParams) ([]GetVotingTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, getVotingTargets, arg.GroupID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVotingTargetsRow{}
	for rows.Next() {
		var i GetVotingTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarEmoji,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isBlockedEitherWay = `-- name: IsBlockedEitherWay :one
SELECT EXISTS (
  SELECT 1 FROM blocks
  WHERE (blocker_id = $1 AND blocked_id = $2)
     OR (blocker_id = $2 AND blocked_id = $1)
)
`

type IsBlockedEitherWayParams struct {
	BlockerID string `json:"blocker_id"`
	BlockedID string `json:"blocked_id"`
}

// A block's effect is symmetric even though only one person created it.
func (q *Queries) IsBlockedEitherWay(ctx context.Context, arg IsBlockedEitherWayParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isBlockedEitherWay, arg.BlockerID, arg.BlockedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isGroupBanned = `-- name: IsGroupBanned :one
SELECT EXISTS (SELECT 1 FROM group_bans WHERE group_id = $1 AND user_id = $2)
`

type IsGroupBannedParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) IsGroupBanned(ctx context.Context, arg IsGroupBannedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isGroupBanned, arg.GroupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBlockedUserIDs = `-- name: ListBlockedUserIDs :many
SELECT (CASE WHEN b.blocker_id = $1 THEN b.blocked_id ELSE b.blocker_id END)::text AS user_id
FROM blocks b
WHERE b.blocker_id = $1 OR b.blocked_id = $1
`

// Everyone this user cannot interact with, in either direction.
// One scan with a CASE rather than a UNION of two scans: the UNION form also confuses sqlc's
// analyzer about which branch an unqualified column belongs to.
// The cast is needed: without it sqlc cannot infer the CASE expression's type.
func (q *Queries) ListBlockedUserIDs(ctx context.Context, blockerID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBlockedUserIDs, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserReports = `-- name: ListUserReports :many
SELECT ur.id, ur.reported_id, ur.reporter_id, ur.group_id, ur.reason, ur.created_at,
       reported.username AS reported_username,
       reporter.username AS reporter_username
FROM user_reports ur
JOIN users reported ON reported.id = ur.reported_id
JOIN users reporter ON reporter.id = ur.reporter_id
ORDER BY ur.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUserReportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUserReportsRow struct {
	ID               string         `json:"id"`
	ReportedID       string         `json:"reported_id"`
	ReporterID       string         `json:"reporter_id"`
	GroupID          sql.NullString `json:"group_id"`
	Reason           sql.NullString `json:"reason"`
	CreatedAt        time.Time      `json:"created_at"`
	ReportedUsername string         `json:"reported_username"`
	ReporterUsername string         `json:"reporter_username"`
}

func (q *Queries) ListUserReports(ctx context.Context, arg ListUserReportsParams) ([]ListUserReportsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserReportsRow{}
	for rows.Next() {
		var i ListUserReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReportedID,
			&i.ReporterID,
			&i.GroupID,
			&i.Reason,
			&i.CreatedAt,
			&i.ReportedUsername,
			&i.ReporterUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
