// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seasons.sql

package db

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const countSeasonVoters = `-- name: CountSeasonVoters :one
SELECT COUNT(DISTINCT voter_id) FROM votes WHERE season_id = $1
`

func (q *Queries) CountSeasonVoters(ctx context.Context, seasonID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSeasonVoters, seasonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSeason = `-- name: CreateSeason :one
INSERT INTO seasons (id, group_id, number, starts_at, reveal_at, ends_at, kind)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, group_id, number, status, starts_at, reveal_at, ends_at, created_at, kind, postpone_count
`

type CreateSeasonParams struct {
	ID       string     `json:"id"`
	GroupID  string     `json:"group_id"`
	Number   int32      `json:"number"`
	StartsAt time.Time  `json:"starts_at"`
	RevealAt time.Time  `json:"reveal_at"`
	EndsAt   time.Time  `json:"ends_at"`
	Kind     SeasonKind `json:"kind"`
}

func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, createSeason,
		arg.ID,
		arg.GroupID,
		arg.Number,
		arg.StartsAt,
		arg.RevealAt,
		arg.EndsAt,
		arg.Kind,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Number,
		&i.Status,
		&i.StartsAt,
		&i.RevealAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.Kind,
		&i.PostponeCount,
	)
	return i, err
}

const getActiveSeasonByGroup = `-- name: GetActiveSeasonByGroup :one
SELECT id, group_id, number, status, starts_at, reveal_at, ends_at, created_at, kind, postpone_count FROM seasons WHERE group_id = $1 AND status = 'VOTING' LIMIT 1
`

func (q *Queries) GetActiveSeasonByGroup(ctx context.Context, groupID string) (Season, error) {
	row := q.db.QueryRowContext(ctx, getActiveSeasonByGroup, groupID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Number,
		&i.Status,
		&i.StartsAt,
		&i.RevealAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.Kind,
		&i.PostponeCount,
	)
	return i, err
}

const getGroupsNeedingNewSeason = `-- name: GetGroupsNeedingNewSeason :many
SELECT DISTINCT g.id, g.name, g.invite_code, g.admin_id, g.telegram_chat_id, g.telegram_chat_username, g.telegram_connect_code, g.telegram_connect_expiry, g.created_at, g.categories, g.kind_only FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE NOT EXISTS (SELECT 1 FROM seasons s WHERE s.group_id = g.id AND s.status = 'VOTING')
GROUP BY g.id HAVING COUNT(gm.id) >= 3
`

func (q *Queries) GetGroupsNeedingNewSeason(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsNeedingNewSeason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.AdminID,
			&i.TelegramChatID,
			&i.TelegramChatUsername,
			&i.TelegramConnectCode,
			&i.TelegramConnectExpiry,
			&i.CreatedAt,
			pq.Array(&i.Categories),
			&i.KindOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsNeedingSeasonMaintenance = `-- name: GetGroupsNeedingSeasonMaintenance :many
SELECT g.id, g.name, g.invite_code, g.admin_id, g.telegram_chat_id, g.telegram_chat_username, g.telegram_connect_code, g.telegram_connect_expiry, g.created_at, g.categories, g.kind_only FROM groups g
WHERE (SELECT COUNT(*) FROM group_members gm WHERE gm.group_id = g.id) >= 3
  AND NOT EXISTS (SELECT 1 FROM seasons s WHERE s.group_id = g.id AND s.status = 'VOTING')
  AND COALESCE(
        (SELECT MAX(s.ends_at) FROM seasons s WHERE s.group_id = g.id),
        TIMESTAMPTZ '-infinity'
      ) < NOW() - INTERVAL '1 hour'
`

// Safety net for the hourly cron: eligible groups with no open season whose most
// recent season finished more than an hour ago (so it never races the Sunday cron
// or the post-kickoff follow-up).
func (q *Queries) GetGroupsNeedingSeasonMaintenance(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsNeedingSeasonMaintenance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.AdminID,
			&i.TelegramChatID,
			&i.TelegramChatUsername,
			&i.TelegramConnectCode,
			&i.TelegramConnectExpiry,
			&i.CreatedAt,
			pq.Array(&i.Categories),
			&i.KindOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastNRevealedSeasons = `-- name: GetLastNRevealedSeasons :many
SELECT id, group_id, number, status, starts_at, reveal_at, ends_at, created_at, kind, postpone_count FROM seasons
WHERE group_id = $1 AND status IN ('REVEALED', 'CLOSED')
ORDER BY number DESC
LIMIT $2
`

type GetLastNRevealedSeasonsParams struct {
	GroupID string `json:"group_id"`
	Limit   int32  `json:"limit"`
}

// CLOSED as well as REVEALED, for the same reason as GetPreviousRevealedSeason: the multi-season
// achievements that read this found no prior seasons and could never fire.
func (q *Queries) GetLastNRevealedSeasons(ctx context.Context, arg GetLastNRevealedSeasonsParams) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, getLastNRevealedSeasons, arg.GroupID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Number,
			&i.Status,
			&i.StartsAt,
			&i.RevealAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.Kind,
			&i.PostponeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastSeasonNumber = `-- name: GetLastSeasonNumber :one
SELECT COALESCE(MAX(number), 0)::int FROM seasons WHERE group_id = $1
`

func (q *Queries) GetLastSeasonNumber(ctx context.Context, groupID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getLastSeasonNumber, groupID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getPreviousRevealedSeason = `-- name: GetPreviousRevealedSeason :one
SELECT id, group_id, number, status, starts_at, reveal_at, ends_at, created_at, kind, postpone_count FROM seasons
WHERE group_id = $1 AND status IN ('REVEALED', 'CLOSED') AND id != $2
ORDER BY number DESC LIMIT 1
`

type GetPreviousRevealedSeasonParams struct {
	GroupID string `json:"group_id"`
	ID      string `json:"id"`
}

// CLOSED as well as REVEALED. This runs at reveal time, when the current season is the REVEALED one
// and every earlier season has already been closed by createSeasonForGroup — so filtering on REVEALED
// alone returned no rows, and the trend line it feeds never rendered.
func (q *Queries) GetPreviousRevealedSeason(ctx context.Context, arg GetPreviousRevealedSeasonParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, getPreviousRevealedSeason, arg.GroupID, arg.ID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Number,
		&i.Status,
		&i.StartsAt,
		&i.RevealAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.Kind,
		&i.PostponeCount,
	)
	return i, err
}

const getRevealedSeasonsForGroup = `-- name: GetRevealedSeasonsForGroup :many
SELECT id, group_id, number, status, starts_at, reveal_at, ends_at, created_at, kind, postpone_count FROM seasons
WHERE group_id = $1 AND status = 'REVEALED'
ORDER BY number DESC
`

// Deliberately REVEALED only: this is the closing step itself, finding the seasons to mark CLOSED.
func (q *Queries) GetRevealedSeasonsForGroup(ctx context.Context, groupID string) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, getRevealedSeasonsForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Number,
			&i.Status,
			&i.StartsAt,
			&i.RevealAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.Kind,
			&i.PostponeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonByID = `-- name: GetSeasonByID :one
SELECT id, group_id, number, status, starts_at, reveal_at, ends_at, created_at, kind, postpone_count FROM seasons WHERE id = $1
`

func (q *Queries) GetSeasonByID(ctx context.Context, id string) (Season, error) {
	row := q.db.QueryRowContext(ctx, getSeasonByID, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Number,
		&i.Status,
		&i.StartsAt,
		&i.RevealAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.Kind,
		&i.PostponeCount,
	)
	return i, err
}

const getSeasonsForReveal = `-- name: GetSeasonsForReveal :many
SELECT id, group_id, number, status, starts_at, reveal_at, ends_at, created_at, kind, postpone_count FROM seasons WHERE status = 'VOTING' AND reveal_at <= NOW()
`

func (q *Queries) GetSeasonsForReveal(ctx context.Context) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, getSeasonsForReveal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Number,
			&i.Status,
			&i.StartsAt,
			&i.RevealAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.Kind,
			&i.PostponeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserVotedInSeason = `-- name: HasUserVotedInSeason :one
SELECT COUNT(*) FROM votes WHERE season_id = $1 AND voter_id = $2
`

type HasUserVotedInSeasonParams struct {
	SeasonID string `json:"season_id"`
	VoterID  string `json:"voter_id"`
}

func (q *Queries) HasUserVotedInSeason(ctx context.Context, arg HasUserVotedInSeasonParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasUserVotedInSeason, arg.SeasonID, arg.VoterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const postponeSeason = `-- name: PostponeSeason :one
UPDATE seasons
SET reveal_at = $1, ends_at = $2, postpone_count = postpone_count + 1
WHERE id = $3 AND status = 'VOTING'
RETURNING id, group_id, number, status, starts_at, reveal_at, ends_at, created_at, kind, postpone_count
`

type PostponeSeasonParams struct {
	RevealAt time.Time `json:"reveal_at"`
	EndsAt   time.Time `json:"ends_at"`
	ID       string    `json:"id"`
}

func (q *Queries) PostponeSeason(ctx context.Context, arg PostponeSeasonParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, postponeSeason, arg.RevealAt, arg.EndsAt, arg.ID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Number,
		&i.Status,
		&i.StartsAt,
		&i.RevealAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.Kind,
		&i.PostponeCount,
	)
	return i, err
}

const scheduleKickoffReveal = `-- name: ScheduleKickoffReveal :one
UPDATE seasons
SET reveal_at = $1, ends_at = GREATEST(ends_at, $2)
WHERE id = $3
  AND kind = 'KICKOFF'
  AND status = 'VOTING'
  AND reveal_at > $1
RETURNING id, group_id, number, status, starts_at, reveal_at, ends_at, created_at, kind, postpone_count
`

type ScheduleKickoffRevealParams struct {
	RevealAt time.Time `json:"reveal_at"`
	EndsAt   time.Time `json:"ends_at"`
	ID       string    `json:"id"`
}

// Brings a kickoff season's reveal forward. The reveal_at > @reveal_at guard makes
// this idempotent and keeps later voters from pushing the time back.
func (q *Queries) ScheduleKickoffReveal(ctx context.Context, arg ScheduleKickoffRevealParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, scheduleKickoffReveal, arg.RevealAt, arg.EndsAt, arg.ID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Number,
		&i.Status,
		&i.StartsAt,
		&i.RevealAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.Kind,
		&i.PostponeCount,
	)
	return i, err
}

const updateSeasonStatus = `-- name: UpdateSeasonStatus :exec
UPDATE seasons SET status = $2 WHERE id = $1
`

type UpdateSeasonStatusParams struct {
	ID     string       `json:"id"`
	Status SeasonStatus `json:"status"`
}

func (q *Queries) UpdateSeasonStatus(ctx context.Context, arg UpdateSeasonStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSeasonStatus, arg.ID, arg.Status)
	return err
}
