// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: season_questions.sql

package db

import (
	"context"
)

const addSeasonQuestion = `-- name: AddSeasonQuestion :one
INSERT INTO season_questions (id, season_id, question_id, ord)
VALUES ($1, $2, $3, $4) RETURNING id, season_id, question_id, ord
`

type AddSeasonQuestionParams struct {
	ID         string `json:"id"`
	SeasonID   string `json:"season_id"`
	QuestionID string `json:"question_id"`
	Ord        int32  `json:"ord"`
}

func (q *Queries) AddSeasonQuestion(ctx context.Context, arg AddSeasonQuestionParams) (SeasonQuestion, error) {
	row := q.db.QueryRowContext(ctx, addSeasonQuestion,
		arg.ID,
		arg.SeasonID,
		arg.QuestionID,
		arg.Ord,
	)
	var i SeasonQuestion
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.QuestionID,
		&i.Ord,
	)
	return i, err
}

const getSeasonQuestions = `-- name: GetSeasonQuestions :many
SELECT q.id, q.text, q.category, q.source, q.group_id, q.author_id, q.status, q.created_at FROM questions q
JOIN season_questions sq ON sq.question_id = q.id
WHERE sq.season_id = $1
ORDER BY sq.ord ASC
`

func (q *Queries) GetSeasonQuestions(ctx context.Context, seasonID string) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getSeasonQuestions, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Category,
			&i.Source,
			&i.GroupID,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
