// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package db

import (
	"context"
	"time"
)

const createSeason = `-- name: CreateSeason :one
INSERT INTO seasons (id, group_id, number, starts_at, reveal_at, ends_at)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, group_id, number, status, starts_at, reveal_at, ends_at, created_at
`

type CreateSeasonParams struct {
	ID       string    `json:"id"`
	GroupID  string    `json:"group_id"`
	Number   int32     `json:"number"`
	StartsAt time.Time `json:"starts_at"`
	RevealAt time.Time `json:"reveal_at"`
	EndsAt   time.Time `json:"ends_at"`
}

func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRowContext(ctx, createSeason,
		arg.ID,
		arg.GroupID,
		arg.Number,
		arg.StartsAt,
		arg.RevealAt,
		arg.EndsAt,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Number,
		&i.Status,
		&i.StartsAt,
		&i.RevealAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSeasonByGroup = `-- name: GetActiveSeasonByGroup :one
SELECT id, group_id, number, status, starts_at, reveal_at, ends_at, created_at FROM seasons WHERE group_id = $1 AND status = 'VOTING' LIMIT 1
`

func (q *Queries) GetActiveSeasonByGroup(ctx context.Context, groupID string) (Season, error) {
	row := q.db.QueryRowContext(ctx, getActiveSeasonByGroup, groupID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Number,
		&i.Status,
		&i.StartsAt,
		&i.RevealAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupsNeedingNewSeason = `-- name: GetGroupsNeedingNewSeason :many
SELECT DISTINCT g.id, g.name, g.invite_code, g.admin_id, g.telegram_chat_id, g.telegram_chat_username, g.telegram_connect_code, g.telegram_connect_expiry, g.created_at FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE NOT EXISTS (SELECT 1 FROM seasons s WHERE s.group_id = g.id AND s.status = 'VOTING')
GROUP BY g.id HAVING COUNT(gm.id) >= 3
`

func (q *Queries) GetGroupsNeedingNewSeason(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsNeedingNewSeason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InviteCode,
			&i.AdminID,
			&i.TelegramChatID,
			&i.TelegramChatUsername,
			&i.TelegramConnectCode,
			&i.TelegramConnectExpiry,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonByID = `-- name: GetSeasonByID :one
SELECT id, group_id, number, status, starts_at, reveal_at, ends_at, created_at FROM seasons WHERE id = $1
`

func (q *Queries) GetSeasonByID(ctx context.Context, id string) (Season, error) {
	row := q.db.QueryRowContext(ctx, getSeasonByID, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Number,
		&i.Status,
		&i.StartsAt,
		&i.RevealAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSeasonsForReveal = `-- name: GetSeasonsForReveal :many
SELECT id, group_id, number, status, starts_at, reveal_at, ends_at, created_at FROM seasons WHERE status = 'VOTING' AND reveal_at <= NOW()
`

func (q *Queries) GetSeasonsForReveal(ctx context.Context) ([]Season, error) {
	rows, err := q.db.QueryContext(ctx, getSeasonsForReveal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Number,
			&i.Status,
			&i.StartsAt,
			&i.RevealAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeasonStatus = `-- name: UpdateSeasonStatus :exec
UPDATE seasons SET status = $2 WHERE id = $1
`

type UpdateSeasonStatusParams struct {
	ID     string       `json:"id"`
	Status SeasonStatus `json:"status"`
}

func (q *Queries) UpdateSeasonStatus(ctx context.Context, arg UpdateSeasonStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSeasonStatus, arg.ID, arg.Status)
	return err
}
