// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_events.sql

package db

import (
	"context"
)

const countJoinsBySource = `-- name: CountJoinsBySource :many
SELECT join_source, COUNT(*)::bigint AS count
FROM group_members
GROUP BY join_source
ORDER BY count DESC
`

type CountJoinsBySourceRow struct {
	JoinSource JoinSource `json:"join_source"`
	Count      int64      `json:"count"`
}

// Memberships grouped by how the member arrived. Compared against CountSharesByChannel to
// judge the loop from a shared card to a joined member.
func (q *Queries) CountJoinsBySource(ctx context.Context) ([]CountJoinsBySourceRow, error) {
	rows, err := q.db.QueryContext(ctx, countJoinsBySource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJoinsBySourceRow{}
	for rows.Next() {
		var i CountJoinsBySourceRow
		if err := rows.Scan(&i.JoinSource, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSharesByChannel = `-- name: CountSharesByChannel :many
SELECT channel, COUNT(*)::bigint AS count
FROM share_events
GROUP BY channel
ORDER BY count DESC
`

type CountSharesByChannelRow struct {
	Channel string `json:"channel"`
	Count   int64  `json:"count"`
}

// Shares grouped by channel, for the acquisition funnel in admin stats.
func (q *Queries) CountSharesByChannel(ctx context.Context) ([]CountSharesByChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, countSharesByChannel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSharesByChannelRow{}
	for rows.Next() {
		var i CountSharesByChannelRow
		if err := rows.Scan(&i.Channel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSharesBySeason = `-- name: CountSharesBySeason :one
SELECT COUNT(*)::bigint FROM share_events WHERE season_id = $1
`

func (q *Queries) CountSharesBySeason(ctx context.Context, seasonID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSharesBySeason, seasonID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createShareEvent = `-- name: CreateShareEvent :one
INSERT INTO share_events (id, user_id, season_id, channel)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, season_id, channel, created_at
`

type CreateShareEventParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	SeasonID string `json:"season_id"`
	Channel  string `json:"channel"`
}

func (q *Queries) CreateShareEvent(ctx context.Context, arg CreateShareEventParams) (ShareEvent, error) {
	row := q.db.QueryRowContext(ctx, createShareEvent,
		arg.ID,
		arg.UserID,
		arg.SeasonID,
		arg.Channel,
	)
	var i ShareEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeasonID,
		&i.Channel,
		&i.CreatedAt,
	)
	return i, err
}
