// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, phone, apple_id, google_id, username, avatar_emoji, birth_year)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, phone, apple_id, google_id, username, avatar_url, avatar_emoji, birth_year, created_at, updated_at, username_changed_at
`

type CreateUserParams struct {
	ID          string         `json:"id"`
	Phone       sql.NullString `json:"phone"`
	AppleID     sql.NullString `json:"apple_id"`
	GoogleID    sql.NullString `json:"google_id"`
	Username    string         `json:"username"`
	AvatarEmoji sql.NullString `json:"avatar_emoji"`
	BirthYear   sql.NullInt32  `json:"birth_year"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Phone,
		arg.AppleID,
		arg.GoogleID,
		arg.Username,
		arg.AvatarEmoji,
		arg.BirthYear,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AppleID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarEmoji,
		&i.BirthYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameChangedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByAppleID = `-- name: GetUserByAppleID :one
SELECT id, phone, apple_id, google_id, username, avatar_url, avatar_emoji, birth_year, created_at, updated_at, username_changed_at FROM users WHERE apple_id = $1
`

func (q *Queries) GetUserByAppleID(ctx context.Context, appleID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAppleID, appleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AppleID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarEmoji,
		&i.BirthYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameChangedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, phone, apple_id, google_id, username, avatar_url, avatar_emoji, birth_year, created_at, updated_at, username_changed_at FROM users WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AppleID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarEmoji,
		&i.BirthYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameChangedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, apple_id, google_id, username, avatar_url, avatar_emoji, birth_year, created_at, updated_at, username_changed_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AppleID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarEmoji,
		&i.BirthYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameChangedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, apple_id, google_id, username, avatar_url, avatar_emoji, birth_year, created_at, updated_at, username_changed_at FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AppleID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarEmoji,
		&i.BirthYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameChangedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, phone, apple_id, google_id, username, avatar_url, avatar_emoji, birth_year, created_at, updated_at, username_changed_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AppleID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarEmoji,
		&i.BirthYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameChangedAt,
	)
	return i, err
}

const updateUserAvatarURL = `-- name: UpdateUserAvatarURL :one
UPDATE users SET avatar_url = $2, updated_at = NOW() WHERE id = $1 RETURNING id, phone, apple_id, google_id, username, avatar_url, avatar_emoji, birth_year, created_at, updated_at, username_changed_at
`

type UpdateUserAvatarURLParams struct {
	ID        string         `json:"id"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) UpdateUserAvatarURL(ctx context.Context, arg UpdateUserAvatarURLParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAvatarURL, arg.ID, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AppleID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarEmoji,
		&i.BirthYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameChangedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET username = $2, avatar_emoji = $3, avatar_url = $4,
  birth_year = $5, updated_at = NOW() WHERE id = $1 RETURNING id, phone, apple_id, google_id, username, avatar_url, avatar_emoji, birth_year, created_at, updated_at, username_changed_at
`

type UpdateUserProfileParams struct {
	ID          string         `json:"id"`
	Username    string         `json:"username"`
	AvatarEmoji sql.NullString `json:"avatar_emoji"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	BirthYear   sql.NullInt32  `json:"birth_year"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.Username,
		arg.AvatarEmoji,
		arg.AvatarUrl,
		arg.BirthYear,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AppleID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarEmoji,
		&i.BirthYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameChangedAt,
	)
	return i, err
}

const updateUserProfileWithUsername = `-- name: UpdateUserProfileWithUsername :one
UPDATE users SET username = $2, avatar_emoji = $3, avatar_url = $4,
  birth_year = $5, username_changed_at = NOW(), updated_at = NOW() WHERE id = $1 RETURNING id, phone, apple_id, google_id, username, avatar_url, avatar_emoji, birth_year, created_at, updated_at, username_changed_at
`

type UpdateUserProfileWithUsernameParams struct {
	ID          string         `json:"id"`
	Username    string         `json:"username"`
	AvatarEmoji sql.NullString `json:"avatar_emoji"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	BirthYear   sql.NullInt32  `json:"birth_year"`
}

func (q *Queries) UpdateUserProfileWithUsername(ctx context.Context, arg UpdateUserProfileWithUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfileWithUsername,
		arg.ID,
		arg.Username,
		arg.AvatarEmoji,
		arg.AvatarUrl,
		arg.BirthYear,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.AppleID,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.AvatarEmoji,
		&i.BirthYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UsernameChangedAt,
	)
	return i, err
}
