// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_group_stats.sql

package db

import (
	"context"
)

const getUserGroupStats = `-- name: GetUserGroupStats :one
SELECT id, user_id, group_id, seasons_played, voting_streak, max_voting_streak, guess_accuracy, total_votes_cast, total_votes_received, updated_at FROM user_group_stats WHERE user_id = $1 AND group_id = $2
`

type GetUserGroupStatsParams struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) GetUserGroupStats(ctx context.Context, arg GetUserGroupStatsParams) (UserGroupStat, error) {
	row := q.db.QueryRowContext(ctx, getUserGroupStats, arg.UserID, arg.GroupID)
	var i UserGroupStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.SeasonsPlayed,
		&i.VotingStreak,
		&i.MaxVotingStreak,
		&i.GuessAccuracy,
		&i.TotalVotesCast,
		&i.TotalVotesReceived,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserGroupStats = `-- name: UpsertUserGroupStats :one
INSERT INTO user_group_stats (id, user_id, group_id, seasons_played, voting_streak, max_voting_streak, guess_accuracy, total_votes_cast, total_votes_received)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, group_id) DO UPDATE SET
  seasons_played = EXCLUDED.seasons_played,
  voting_streak = EXCLUDED.voting_streak,
  max_voting_streak = EXCLUDED.max_voting_streak,
  guess_accuracy = EXCLUDED.guess_accuracy,
  total_votes_cast = EXCLUDED.total_votes_cast,
  total_votes_received = EXCLUDED.total_votes_received,
  updated_at = NOW()
RETURNING id, user_id, group_id, seasons_played, voting_streak, max_voting_streak, guess_accuracy, total_votes_cast, total_votes_received, updated_at
`

type UpsertUserGroupStatsParams struct {
	ID                 string  `json:"id"`
	UserID             string  `json:"user_id"`
	GroupID            string  `json:"group_id"`
	SeasonsPlayed      int32   `json:"seasons_played"`
	VotingStreak       int32   `json:"voting_streak"`
	MaxVotingStreak    int32   `json:"max_voting_streak"`
	GuessAccuracy      float64 `json:"guess_accuracy"`
	TotalVotesCast     int32   `json:"total_votes_cast"`
	TotalVotesReceived int32   `json:"total_votes_received"`
}

func (q *Queries) UpsertUserGroupStats(ctx context.Context, arg UpsertUserGroupStatsParams) (UserGroupStat, error) {
	row := q.db.QueryRowContext(ctx, upsertUserGroupStats,
		arg.ID,
		arg.UserID,
		arg.GroupID,
		arg.SeasonsPlayed,
		arg.VotingStreak,
		arg.MaxVotingStreak,
		arg.GuessAccuracy,
		arg.TotalVotesCast,
		arg.TotalVotesReceived,
	)
	var i UserGroupStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.SeasonsPlayed,
		&i.VotingStreak,
		&i.MaxVotingStreak,
		&i.GuessAccuracy,
		&i.TotalVotesCast,
		&i.TotalVotesReceived,
		&i.UpdatedAt,
	)
	return i, err
}
