// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_group_stats.sql

package db

import (
	"context"
	"database/sql"
)

const getGroupGuessStanding = `-- name: GetGroupGuessStanding :many
SELECT u.id, u.username, u.avatar_emoji,
  ugs.guess_accuracy, ugs.seasons_played
FROM group_members gm
JOIN users u ON u.id = gm.user_id
LEFT JOIN user_group_stats ugs ON ugs.user_id = gm.user_id AND ugs.group_id = gm.group_id
WHERE gm.group_id = $1
ORDER BY ugs.guess_accuracy DESC NULLS LAST, u.username ASC
`

type GetGroupGuessStandingRow struct {
	ID            string          `json:"id"`
	Username      string          `json:"username"`
	AvatarEmoji   sql.NullString  `json:"avatar_emoji"`
	GuessAccuracy sql.NullFloat64 `json:"guess_accuracy"`
	SeasonsPlayed sql.NullInt32   `json:"seasons_played"`
}

// Every current member of the group with their stored guess accuracy.
//
// A LEFT JOIN on purpose: a member who has not yet been through a reveal has no stats row, and that is
// how "not yet ranked" is expressed. Defaulting them to zero would rank them last on a number nobody
// measured.
//
// The accuracy is read, never recomputed: the stored value is a rolling average over a 5-season
// window (see internal/service/achievements), so recomputing here would show a different number than
// the profile does.
func (q *Queries) GetGroupGuessStanding(ctx context.Context, groupID string) ([]GetGroupGuessStandingRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupGuessStanding, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupGuessStandingRow{}
	for rows.Next() {
		var i GetGroupGuessStandingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarEmoji,
			&i.GuessAccuracy,
			&i.SeasonsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroupStats = `-- name: GetUserGroupStats :one
SELECT id, user_id, group_id, seasons_played, voting_streak, max_voting_streak, guess_accuracy, total_votes_cast, total_votes_received, updated_at FROM user_group_stats WHERE user_id = $1 AND group_id = $2
`

type GetUserGroupStatsParams struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) GetUserGroupStats(ctx context.Context, arg GetUserGroupStatsParams) (UserGroupStat, error) {
	row := q.db.QueryRowContext(ctx, getUserGroupStats, arg.UserID, arg.GroupID)
	var i UserGroupStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.SeasonsPlayed,
		&i.VotingStreak,
		&i.MaxVotingStreak,
		&i.GuessAccuracy,
		&i.TotalVotesCast,
		&i.TotalVotesReceived,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserGroupStats = `-- name: UpsertUserGroupStats :one
INSERT INTO user_group_stats (id, user_id, group_id, seasons_played, voting_streak, max_voting_streak, guess_accuracy, total_votes_cast, total_votes_received)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, group_id) DO UPDATE SET
  seasons_played = EXCLUDED.seasons_played,
  voting_streak = EXCLUDED.voting_streak,
  max_voting_streak = EXCLUDED.max_voting_streak,
  guess_accuracy = EXCLUDED.guess_accuracy,
  total_votes_cast = EXCLUDED.total_votes_cast,
  total_votes_received = EXCLUDED.total_votes_received,
  updated_at = NOW()
RETURNING id, user_id, group_id, seasons_played, voting_streak, max_voting_streak, guess_accuracy, total_votes_cast, total_votes_received, updated_at
`

type UpsertUserGroupStatsParams struct {
	ID                 string  `json:"id"`
	UserID             string  `json:"user_id"`
	GroupID            string  `json:"group_id"`
	SeasonsPlayed      int32   `json:"seasons_played"`
	VotingStreak       int32   `json:"voting_streak"`
	MaxVotingStreak    int32   `json:"max_voting_streak"`
	GuessAccuracy      float64 `json:"guess_accuracy"`
	TotalVotesCast     int32   `json:"total_votes_cast"`
	TotalVotesReceived int32   `json:"total_votes_received"`
}

func (q *Queries) UpsertUserGroupStats(ctx context.Context, arg UpsertUserGroupStatsParams) (UserGroupStat, error) {
	row := q.db.QueryRowContext(ctx, upsertUserGroupStats,
		arg.ID,
		arg.UserID,
		arg.GroupID,
		arg.SeasonsPlayed,
		arg.VotingStreak,
		arg.MaxVotingStreak,
		arg.GuessAccuracy,
		arg.TotalVotesCast,
		arg.TotalVotesReceived,
	)
	var i UserGroupStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.SeasonsPlayed,
		&i.VotingStreak,
		&i.MaxVotingStreak,
		&i.GuessAccuracy,
		&i.TotalVotesCast,
		&i.TotalVotesReceived,
		&i.UpdatedAt,
	)
	return i, err
}
