// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: votes.sql

package db

import (
	"context"
)

const aggregateVotesByTarget = `-- name: AggregateVotesByTarget :many
SELECT target_id, question_id, COUNT(*) as vote_count
FROM votes WHERE season_id = $1
GROUP BY target_id, question_id
`

type AggregateVotesByTargetRow struct {
	TargetID   string `json:"target_id"`
	QuestionID string `json:"question_id"`
	VoteCount  int64  `json:"vote_count"`
}

func (q *Queries) AggregateVotesByTarget(ctx context.Context, seasonID string) ([]AggregateVotesByTargetRow, error) {
	rows, err := q.db.QueryContext(ctx, aggregateVotesByTarget, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateVotesByTargetRow{}
	for rows.Next() {
		var i AggregateVotesByTargetRow
		if err := rows.Scan(&i.TargetID, &i.QuestionID, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUniqueVoters = `-- name: CountUniqueVoters :one
SELECT COUNT(DISTINCT voter_id) FROM votes WHERE season_id = $1
`

func (q *Queries) CountUniqueVoters(ctx context.Context, seasonID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUniqueVoters, seasonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVote = `-- name: CreateVote :one
INSERT INTO votes (id, season_id, voter_id, target_id, question_id)
VALUES ($1, $2, $3, $4, $5) RETURNING id, season_id, voter_id, target_id, question_id, created_at
`

type CreateVoteParams struct {
	ID         string `json:"id"`
	SeasonID   string `json:"season_id"`
	VoterID    string `json:"voter_id"`
	TargetID   string `json:"target_id"`
	QuestionID string `json:"question_id"`
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRowContext(ctx, createVote,
		arg.ID,
		arg.SeasonID,
		arg.VoterID,
		arg.TargetID,
		arg.QuestionID,
	)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.VoterID,
		&i.TargetID,
		&i.QuestionID,
		&i.CreatedAt,
	)
	return i, err
}

const getVotersBySeason = `-- name: GetVotersBySeason :many
SELECT DISTINCT voter_id FROM votes WHERE season_id = $1
`

func (q *Queries) GetVotersBySeason(ctx context.Context, seasonID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getVotersBySeason, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var voter_id string
		if err := rows.Scan(&voter_id); err != nil {
			return nil, err
		}
		items = append(items, voter_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVotesBySeasonAndVoter = `-- name: GetVotesBySeasonAndVoter :many
SELECT id, season_id, voter_id, target_id, question_id, created_at FROM votes WHERE season_id = $1 AND voter_id = $2
`

type GetVotesBySeasonAndVoterParams struct {
	SeasonID string `json:"season_id"`
	VoterID  string `json:"voter_id"`
}

func (q *Queries) GetVotesBySeasonAndVoter(ctx context.Context, arg GetVotesBySeasonAndVoterParams) ([]Vote, error) {
	rows, err := q.db.QueryContext(ctx, getVotesBySeasonAndVoter, arg.SeasonID, arg.VoterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vote{}
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.VoterID,
			&i.TargetID,
			&i.QuestionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
